-- =============================================================================
-- Acceso-Alarma septiembre 2026 · parte 3 de 3 (86 SKU de 258)
-- Correr DESPUÉS de las 3 partes de Siemon.
-- Copiar este archivo COMPLETO (GitHub Raw → Ctrl+A → Ctrl+C) → SQL Editor → Run.
-- Primero: DS-PK-LRT  ·  Último: UVC-G4
-- costo = lista USD; precio = costo; utilidad = 0. Sin updated_at.
-- =============================================================================
rollback;

begin;

drop table if exists cat_acceso_2026;
create temporary table cat_acceso_2026 (
  marca text not null,
  modelo text not null,
  nombre text not null,
  categoria text not null,
  costo numeric(14,2) not null,
  descripcion text,
  estatus text not null,
  primary key (marca, modelo)
);

insert into cat_acceso_2026 (marca, modelo, nombre, categoria, costo, descripcion, estatus)
values
  ('Hikvision', 'DS-PK-LRT', 'Hikvision DS-PK-LRT Blanco) teclado cableado lcd (color blanco) pantalla lcd 80 x 25 mm', 'Domótica', 35.00, 'Blanco) teclado cableado lcd (color blanco) pantalla lcd 80 x 25 mm. pantalla de 2 lineas armado y desarmado por tarjetas (tag) y/o llaveros (keyfob ds-19k00-y) muestra nombre de zona, estados y eventos en tiempo real en pantalla lcd', 'DISPONIBLE'),
  ('Hikvision', 'DS-PK1-LRT-HWB', 'Hikvision DS-PK1-LRT-HWB Blanco) teclado cableado lcd (color blanco) pantalla lcd. soporta', 'Domótica', 50.00, 'Blanco) teclado cableado lcd (color blanco) pantalla lcd. soporta alarma de 1 toque para armado sin contraseña. soporta 1 tecla para alarma de fuego, panico o medica. visualización de nombre de empresa, número de telefono, hora. posee en tarjeta 2 entradas y 1 salida de alarma. soporta 64 llaveros keyfob. 1 buzzer en tarjeta. sensor anti-vandalismo', 'DISPONIBLE'),
  ('Hikvision', 'DS-PMA-P', 'Hikvision DS-PMA-P Modulo pstn para central hibrida comunicación series port/pstn, linea', 'Domótica', 12.50, 'Modulo pstn para central hibrida comunicación series port/pstn, linea fija de telefono', 'DISPONIBLE'),
  ('Hikvision', 'DS-PM2-S(AU)', 'Hikvision DS-PM2-S(AU) Modulo comunicación 3g/4g central ax hybrid pro comunicador 3g/4g', 'Domótica', 76.00, 'Modulo comunicación 3g/4g central ax hybrid pro comunicador 3g/4g. micro sim. compatible con el panel hybrid pro hikvision ds-pha64-lp. soporte a múltiples operadores celulares. requiere una tarjeta micro sim. modo de comunicación dual-band umts/hsdpa/hspa+b1/b5', 'DISPONIBLE'),
  ('Hikvision', 'DS-PM-RSWR', 'Hikvision DS-PM-RSWR 433mhz) expansor de 8 zonas inalambricas agrega sensores inalambricos a', 'Domótica', 30.00, '433mhz) expansor de 8 zonas inalambricas agrega sensores inalambricos a alarma cableada soporta 8 entradas zonas inalambricas soporta 32 controles remotos y 2 sirenas inalambricas distancia: 400 metros indicador led dual rojo/verde conexión rs-485', 'DISPONIBLE'),
  ('Hikvision', 'DS-PM1-I8O2-H', 'Hikvision DS-PM1-I8O2-H Expansor de 8 zonas cableadas soporta conexión 3eol (alarm ： 1kω ；', 'Domótica', 28.00, 'Expansor de 8 zonas cableadas soporta conexión 3eol (alarm ： 1kω ； tamper ： 1kω ； fault ： 2.2kω). soporta detección de zona de alarma, anti-vandalismo, enmascaramiento, falla y corto. 1 salida de corriente para sensores cableados. soporta otros expansores en cascada. indicadores led para encendido y 1 para falla. carcasa plastica', 'DISPONIBLE'),
  ('Hikvision', 'DS-PM1-RT-HWB', 'Hikvision DS-PM1-RT-HWB Expansor de 32 zonas inalambricas tri-x conexión bus speed-x permite', 'Domótica', 98.00, 'Expansor de 32 zonas inalambricas tri-x conexión bus speed-x permite agregar sensores ax-pro compatible con paneles ax hybrido pro distancia de transmisión hasta 1300 metros fuente de poder: 9 a 28 vdc, 1a soporta hasta 4 sirenas internas y 8 sirenas externas - no disponible teclado cableado led armado, desarmado, despeje, bypass, etc incador de estatus en tiempo real de zonas protección tamper, protocolo rs-485, alimentación 12vdc, 12 teclas: 0 a 9, * y # estatus control de acceso hikvision ds-', 'DISPONIBLE'),
  ('Hikvision', 'DS-PM1-O4L-H', 'Hikvision DS-PM1-O4L-H Rele de baja corriente de 4 vías cableado modulo de 4 reles 6-30v hasta', 'Domótica', 37.50, 'Rele de baja corriente de 4 vías cableado modulo de 4 reles 6-30v hasta 5a 1 salida de potencia maximo 500ma funciones de automatización / domotica comunicación speed-x bus a prueba de vandalismo voltaje de operación 11-24 vcc / 1a', 'DISPONIBLE'),
  ('Hikvision', 'DS-PM1-O4H-H', 'Hikvision DS-PM1-O4H-H Rele de potencia de 4 vías cableado modulo de 4 reles 100 v~240 v hasta', 'Domótica', 37.50, 'Rele de potencia de 4 vías cableado modulo de 4 reles 100 v~240 v hasta 16a 1 puerto serial ttl funciones de automatización / domotica comunicación 2xspeed-x bus, 1 uplink para el control de panel de conexión y 1 downlink para otro expansor a prueba de vandalismo delantero y trasero', 'DISPONIBLE'),
  ('Hikvision', 'DS-PM-RSO4', 'Hikvision DS-PM-RSO4 433mhz) expansor rs-485 con 4 salidas cableadas alta potencia voltaje', 'Domótica', 28.00, '433mhz) expansor rs-485 con 4 salidas cableadas alta potencia voltaje de operacion: 12 v / 1 a 4 salidas de rele no/nc capacidad de los reles: 220vca / 10a', 'DISPONIBLE'),
  ('Hikvision', 'DS-PM-RSO8', 'Hikvision DS-PM-RSO8 433mhz) expansor rs-485 con 8 salidas cableadas alta potencia voltaje', 'Domótica', 39.00, '433mhz) expansor rs-485 con 8 salidas cableadas alta potencia voltaje de operacion: 12 v / 1 a 8 salidas de rele no/nc capacidad de los reles: 220vca / 10a', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDP18-EG2(B)', 'Hikvision DS-PDP18-EG2(B) Detector de movimiento antimascota cableado inmunidad antimascota: 15', 'Domótica', 7.50, 'Detector de movimiento antimascota cableado inmunidad antimascota: 15 kg rango de detección: 18 m, angulo de detección 85.9° compensación digital de temperatura sensor infrarrojo de doble elemento', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDD12P-EG2', 'Hikvision DS-PDD12P-EG2 Detector de movimiento antimascota cableado tecnologia dual: pir y', 'Domótica', 18.00, 'Detector de movimiento antimascota cableado tecnologia dual: pir y microondas inmunidad antimascota: 10 kg rango de detección: 12 m, angulo de detección 85.9° compensación digital de temperatura sensor infrarrojo de doble elemento', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDD12-EG2', 'Hikvision DS-PDD12-EG2 Detector de movimiento antimascota cableado tecnologia dual: pir y', 'Domótica', 21.00, 'Detector de movimiento antimascota cableado tecnologia dual: pir y microondas inmunidad antimascota: 10 kg rango de detección: 12 m, angulo de detección 85.9° compensación digital de temperatura sensor infrarrojo de doble elemento', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDPG12P-EG2', 'Hikvision DS-PDPG12P-EG2 Detector cableado de movimiento + ruptura de cristal inmunidad', 'Domótica', 25.00, 'Detector cableado de movimiento + ruptura de cristal inmunidad antimascota: 30 kg rango de detección: 18m / 90° rango de ruptura de cristal: 8m / 120° sensibilida ajustable voltaje ajustable 9-16 vdc', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDPC12P-EG2', 'Hikvision DS-PDPC12P-EG2 Detector pir cableado + camara integrada rango de detección pir: 12m /', 'Domótica', 65.00, 'Detector pir cableado + camara integrada rango de detección pir: 12m / 85.9° inmunidad antimascota: 30 kg control inteligente de ambiente avanzado digital video: angulo 88°(h), 68°(v) / resolución 640*480 switch dia/noche: color / blanco y negro', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDBG8-EG2', 'Hikvision DS-PDBG8-EG2 Detector de ruptura de cristal cableado sensor microfono', 'Domótica', 15.00, 'Detector de ruptura de cristal cableado sensor microfono omni-direccional de alta calidad configurable remotamente a través de la app rango de detección: 8m / angulo 120° sensibilidad: 2m;4m;6m;8m vidrio: grosor 2.4mm a 6.4mm tamaño: 0.3mx0.3m a 3mx3m', 'DISPONIBLE'),
  ('Hikvision', 'DS-PD1-BG9', 'Hikvision DS-PD1-BG9 Detector de ruptura de cristal cableado voltaje de operación: 9 - 16', 'Domótica', 22.00, 'Detector de ruptura de cristal cableado voltaje de operación: 9 - 16 vdc 25 ma de consumo rango de detección: sensibilidad alta 9 metros, sensibilidad baja 5 metros 2 indicadores led', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDSK-P', 'Hikvision DS-PDSK-P Detector sismico cableado rango de detección : hasta 5m (radio 2.5m)', 'Domótica', 12.50, 'Detector sismico cableado rango de detección : hasta 5m (radio 2.5m) ajsute de sensibilidad para interior indicador led azul antivandalismo', 'DISPONIBLE'),
  ('Hikvision', 'DS-PD1-EB', 'Hikvision DS-PD1-EB Boton de emergencia (panico) carcasa de abs retardante de llama modo de', 'Domótica', 2.00, 'Boton de emergencia (panico) carcasa de abs retardante de llama modo de conexión: no/nc 49.5 mm × 53.5 mm × 32.5 mm', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDSMK-4', 'Hikvision DS-PDSMK-4', 'Domótica', 10.00, '', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDSMK-4BAR', 'Hikvision DS-PDSMK-4BAR Reinicio automatico sirena interna', 'Domótica', 14.50, 'Reinicio automatico sirena interna', 'DISPONIBLE'),
  ('Hikvision', 'DS-PI-T250', 'Hikvision DS-PI-T250 250 metros', 'Domótica', 105.00, '250 metros', 'DISPONIBLE'),
  ('Hikvision', 'DS-PD1-MC-WS', 'Hikvision DS-PD1-MC-WS Contacto magnetico superficial plastico abs conexión: nc diseñado para', 'Domótica', 2.00, 'Contacto magnetico superficial plastico abs conexión: nc diseñado para puertas o ventanas distancia apertura: 1.7 cm dimensiones: 63.5mm x 12.5mm x 15.7mm', 'DISPONIBLE'),
  ('Hikvision', 'DS-PD1-MC-MS', 'Hikvision DS-PD1-MC-MS Contacto magnetico superficial metalico conexión: nc diseñado para', 'Domótica', 5.50, 'Contacto magnetico superficial metalico conexión: nc diseñado para puertas o ventanas distancia apertura: 4 cm dimensiones: 50mm x 18mm x 10mm', 'DISPONIBLE'),
  ('Omegasat', 'OM-SIRENE', 'Omegasat OM-SIRENE Sirena diseño moderno color blanco 1 tono 115db 12vdc 180ma', 'Domótica', 4.00, 'Sirena diseño moderno color blanco 1 tono 115db 12vdc 180ma', 'DISPONIBLE'),
  ('Omegasat', 'OM-SIRENE-Black', 'Omegasat OM-SIRENE-Black Sirena diseño moderno color negro 1 tono 115db 12vdc 180ma', 'Domótica', 4.00, 'Sirena diseño moderno color negro 1 tono 115db 12vdc 180ma', 'DISPONIBLE'),
  ('Hikvision', 'DS-PS3001', 'Hikvision DS-PS3001 Sirena cableada. ideal para cualquier panel de alarma (no importa la', 'Domótica', 13.00, 'Sirena cableada. ideal para cualquier panel de alarma (no importa la marca). 30 watts. 120 db de sonido. protección ip65 (exterior', 'DISPONIBLE'),
  ('Hikvision', 'DS-PKA-WLM-433', 'Hikvision DS-PKA-WLM-433 Negro', 'Domótica', 29.00, 'Negro', 'DISPONIBLE'),
  ('Hikvision', 'DS-PKA-WLM-433-White', 'Hikvision DS-PKA-WLM-433-White Blanco', 'Domótica', 29.00, 'Blanco', 'DISPONIBLE'),
  ('Hikvision', 'DS-PD1-MC-WWS(H)', 'Hikvision DS-PD1-MC-WWS(H) 433mhz) contacto magnetico inalambrico distancia inalambrica de', 'Domótica', 12.50, '433mhz) contacto magnetico inalambrico distancia inalambrica de comunicación: 800 metros alarma tamper, alarma intrusión indicador led de 3 colores', 'DISPONIBLE'),
  ('Hikvision', 'DS-PD1-WL-W', 'Hikvision DS-PD1-WL-W 433mhz) detector de fugas de agua inalambrico distancia soportada 300', 'Domótica', 24.00, '433mhz) detector de fugas de agua inalambrico distancia soportada 300 metros (area abierta), los datos inalambricos estan protegidos por el cifrado aes-128, switch tamper, bateria 1 año (3v, cr2450', 'DISPONIBLE'),
  ('Hikvision', 'DS-19K00-Y', 'Hikvision DS-19K00-Y 433mhz) control remoto (keyfob inalambrico) 5 botones de operación', 'Insumos', 11.00, '433mhz) control remoto (keyfob inalambrico) 5 botones de operación, distancia soportada 300 metros (area abierta), control tipo llavero, indicador led rojo/verde, bateria 210mah (3v, cr2032', 'DISPONIBLE'),
  ('Hikvision', 'DS-PA201P-Kit-16WB', 'Hikvision DS-PA201P-Kit-16WB 433mhz) kit panel de alarma inalambrico ax home 16 zonas incluye: 1', 'Domótica', 110.00, '433mhz) kit panel de alarma inalambrico ax home 16 zonas incluye: 1 central ds-pa201p-16wb / 1 sensor pir inalambrico ds- pd111-10f-wb / 1 contacto magnético inalambrico ds-pd121-wb / 1 control remoto keyfob inalambrico ds-pc120-wb conexión wi-fi 2.4ghz y lan a traves de modulo ds-pc201n incluye bateria de respaldo hasta 12 horas', 'DISPONIBLE'),
  ('Hikvision', 'DS-PC201N', 'Hikvision DS-PC201N MODULO DE CONEXIÓN ETHERNET PARA PANELES AX HOME Compatible con panales', 'Domótica', 10.00, 'MODULO DE CONEXIÓN ETHERNET PARA PANELES AX HOME Compatible con panales AX HOME DS-PA201P-16WB y DS-PA201PS- 16WB/A-LA. Velocidad de transmisión hasta 10 Mbps. Operación confiable de -10 a 55°C. Ligero, solo 6.5 gramos. Dimensiones compactas de 55 x 13.45 x 24 mm', 'DISPONIBLE'),
  ('Hikvision', 'DS-PD201MC-WB', 'Hikvision DS-PD201MC-WB 433mhz) contacto magnetico inlambrico ax home tecnologia inalambrica', 'Domótica', 20.00, '433mhz) contacto magnetico inlambrico ax home tecnologia inalambrica confiable indicador led para alertas visibles voltaje 1.5 vcc con bateria aa espacio de apertura maximo de 25 mm rango rf de 1.2km 16.00 disponible teclado inalambrico led (color negro o blanco) diseño tactil completamente con luz led de fondo 6 teclas de funciones: fire alarm, away arming, stay arming, disarming, delete, and confirm números: 10 teclas, 0 a 9 3 indicadores de estatus: ecendido (verde),falla (naranja), y alarma ', 'DISPONIBLE'),
  ('Hikvision', 'DS-PD201PC10-WB', 'Hikvision DS-PD201PC10-WB 433mhz) detector pir + camara inalambrico ax home 2 años de batería', 'Domótica', 46.00, '433mhz) detector pir + camara inalambrico ax home 2 años de batería. inmunidad a mascotas 24kg. rango de detección de 10 mts. ángulo de 90° de cobertura. uso interior. rango de detección: 10 metros. 90°. altura de instalción 2 - 2.4 m. ajuste de sensibilidad: alta / automatica / baja', 'DISPONIBLE'),
  ('Hikvision', 'DS-PK201B-WB', 'Hikvision DS-PK201B-WB 433mhz) teclado inalambrico para armar y desarmar ax home tecnologia', 'Domótica', 26.00, '433mhz) teclado inalambrico para armar y desarmar ax home tecnologia inalambrica por radiofrecuencia permite operaciones de armado y desarmado operación a 1.5vcc con 4 baterias aa incluidas panel con botones mecanicos, indicadores led, buzzer peso ligero, compacto, portatil', 'DISPONIBLE'),
  ('Hikvision', 'DS-PKF201-WB', 'Hikvision DS-PKF201-WB 433mhz) control remoto keyfob inalambrico ax home para armado y', 'Domótica', 12.00, '433mhz) control remoto keyfob inalambrico ax home para armado y desarmado de forma remota botones configurables para personalización 1 bateria cr2032 (incluida) reemplazable tecnologia inalambrica por radiofrecuencia', 'DISPONIBLE'),
  ('Hikvision', 'DS-PS201-WB/Red', 'Hikvision DS-PS201-WB/Red 433mhz) sirena inalambrica para interior ax home - luz roja volumen', 'Domótica', 26.00, '433mhz) sirena inalambrica para interior ax home - luz roja volumen ajustable entre 80 y 95 db 4 tipos de alarma: fuego, panico, medico, intrusion duracioin de alarma ajustable 10 seg a 15 min funciona con 4 baterías aa, incluidas voltaje de operación: 1.5 vcc, -10 a 55°c', 'DISPONIBLE'),
  ('Hikvision', 'DS-PS201-WB/Blue', 'Hikvision DS-PS201-WB/Blue 433mhz) sirena inalambrica para interior ax home - luz azul volumen', 'Domótica', 26.00, '433mhz) sirena inalambrica para interior ax home - luz azul volumen ajustable entre 80 y 95 db 4 tipos de alarma: fuego, panico, medico, intrusion duracioin de alarma ajustable 10 seg a 15 min funciona con 4 baterías aa, incluidas voltaje de operación: 1.5 vcc, -10 a 55°c', 'DISPONIBLE'),
  ('Hikvision', 'DS-PWA48-E-WB', 'Hikvision DS-PWA48-E-WB 433MHz) PANEL DE ALARMA INALÁMBRICO DE HIKVISION AX PRO Soporta 48', 'Domótica', 104.00, '433MHz) PANEL DE ALARMA INALÁMBRICO DE HIKVISION AX PRO Soporta 48 Zonas. Wi-Fi y Ethernet. Incluye Batería de respaldo. Compatible con los Accesorios AX PRO Soporta hasta 48 zonas o salidas de alarma Visualización de video en cliente móvil y correo Indicación de voz para configuración y operación Configuración a través de web y software cliente Envío de notificaciones push de alarma', 'DISPONIBLE'),
  ('Hikvision', 'DS-PWA48-Kit-WB(LA)', 'Hikvision DS-PWA48-Kit-WB(LA) 433mhz) kit panel de alarma ax pro 48 zonas hasta 800 metros incluye: 1', 'Domótica', 164.00, '433mhz) kit panel de alarma ax pro 48 zonas hasta 800 metros incluye: 1 central hub ds-pwa48-l-wb / 1 sensor pir ds-pdp15p- eg2-wb / 1 contacto magnético ds-pdmc-eg2-wb / 1 control remoto ds-pkf1-wb multiples metodos de comunicación: lan + wi-fi + 3g/4g dual sim card', 'DISPONIBLE'),
  ('Hikvision', 'DS-PWA64-Kit-WB', 'Hikvision DS-PWA64-Kit-WB 433mhz) kit panel de alarma ax pro 64 zonas hasta 800 metros incluye: 1', 'Domótica', 147.50, '433mhz) kit panel de alarma ax pro 64 zonas hasta 800 metros incluye: 1 central hub ds-pwa64-l-wb / 1 sensor pir ds-pdp15p- eg2-wb / 1 contacto magnético ds-pdmc-eg2-wb / 1 control remoto ds-pkf1-wb multiples metodos de comunicación: lan + wi-fi', 'DISPONIBLE'),
  ('Hikvision', 'DS-PWA96-Kit-WB/4G', 'Hikvision DS-PWA96-Kit-WB/4G 433mhz) kit panel de alarma ax pro 96 zonas hasta 800 metros incluye: 1', 'Domótica', 239.00, '433mhz) kit panel de alarma ax pro 96 zonas hasta 800 metros incluye: 1 central hub ds-pwa96-m-wb / 1 sensor pir ds- pdp15p-eg2-wb / 1 contacto magnético ds-pdmc-eg2-wb / 1 control remoto ds-pkf1-wb multiples metodos de comunicación: lan + wi-fi + 3g/4g', 'DISPONIBLE'),
  ('Hikvision', 'DS-PK1-E-WB', 'Hikvision DS-PK1-E-WB 433mhz) teclado inalambrico led configurable remotamento a través de la', 'Domótica', 27.50, '433mhz) teclado inalambrico led configurable remotamento a través de la app operaciones de armado, desarmado, limpiar alarma panel con pantalla tactil teclas con luz led de fondo led para indicar la zona programada voltaje 1.5 vcd / 4 baterias aa (incluidas) activación de 1 toque para alarma de fuego, panico 55.00 disponible hikvision ds ‐ pk1 ‐ lt ‐ wb teclado inalambrico lcd tecnologia inalambrica bidireccional para ax pro pantalla lcd y leds para indicar el estado del sistema. configuración d', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDC15-EG2-WB(B)', 'Hikvision DS-PDC15-EG2-WB(B) 433mhz) detector pir inalambrico tipo cortina rango de detección: 15m /', 'Domótica', 35.00, '433mhz) detector pir inalambrico tipo cortina rango de detección: 15m / 6.3° inmunidad antimascota: 30 kg control inteligente de ambiente avanzado digital 3 ajustes de sensibilidad', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDD12P-EG2-WB', 'Hikvision DS-PDD12P-EG2-WB 433mhz) detector inalambrico movimiento + ruptura de cristal inmunidad', 'Domótica', 62.00, '433mhz) detector inalambrico movimiento + ruptura de cristal inmunidad antimascota: 30 kg rango de detección pir: 18m / 90° rango de ruptura de cristal: 8m / 120° sensibilida ajustable rango rf de 1km', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDPC12P-EG2-WB', 'Hikvision DS-PDPC12P-EG2-WB 433mhz) detector pir inalambrico + camara integrada rango de detección', 'Domótica', 80.00, '433mhz) detector pir inalambrico + camara integrada rango de detección pir: 12m / 85.9° inmunidad antimascota: 30 kg control inteligente de ambiente avanzado digital video: angulo 88°(h), 68°(v) / resolución 640*480 switch dia/noche: color / blanco y negro', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDPC12PF-EG2-WB', 'Hikvision DS-PDPC12PF-EG2-WB 433mhz) detector pir inalambrico + camara integrada colorvu rango de', 'Domótica', 87.00, '433mhz) detector pir inalambrico + camara integrada colorvu rango de detección pir: 12m / 85.9° inmunidad antimascota: 30 kg control inteligente de ambiente avanzado digital video: angulo 88°(h), 68°(v) / resolución 640*480 switch dia/noche: color luz blanca 12m', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDCL12-EG2-WB', 'Hikvision DS-PDCL12-EG2-WB 433mhz) detector inalambrico de movimiento 360° para techo infrarrojo', 'Domótica', 25.00, '433mhz) detector inalambrico de movimiento 360° para techo infrarrojo pasivo con precesamiento digital rango de detección: 12m / 360° sensibilidad: automatica / baja altura de montaje: 2.4 - 4m rango rf de 1km', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDP18-HM-WB', 'Hikvision DS-PDP18-HM-WB 433mhz) detector inalambrico movimiento para exterior doble tecnologia', 'Domótica', 65.00, '433mhz) detector inalambrico movimiento para exterior doble tecnologia am (pir / microondas) inmunidad antimascota: 24 kg rango de detección: 18 m angulo de detección ajustable 90° intemperie ip65 rango rf de 1km / tecnologia tri-x wireless', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDMCS-EG2-WB', 'Hikvision DS-PDMCS-EG2-WB 433mhz) contacto magnetico inlambrico configurable remotamente a través', 'Domótica', 16.00, '433mhz) contacto magnetico inlambrico configurable remotamente a través de la app diseño delgado instalación discreta imperceptible distancia apertura 52mm max entrada de alarma nc / no / impulse count rango rf de 1km', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDMC-EG2-WB', 'Hikvision DS-PDMC-EG2-WB 433mhz) contacto magnetico inlambrico configurable remotamente a través', 'Domótica', 21.00, '433mhz) contacto magnetico inlambrico configurable remotamente a través de la app diseño delgado instalación discreta imperceptible distancia apertura 43mm max entrada de alarma nc / no / impulse count rango rf de 1.2km', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDMCX-E-WB', 'Hikvision DS-PDMCX-E-WB 433mhz) contacto magnetico exterior inlambrico configurable remotamente', 'Domótica', 29.00, '433mhz) contacto magnetico exterior inlambrico configurable remotamente a través de la app intemperie ip66, protección uv distancia apertura 76mm max entrada de alarma nc / no / impulse count rango rf de 1.6km - no disponible estatus control de acceso hikvision ds-pdbg8-eg2-wb (433mhz) detector de ruptura de cristal inalambrico sensor microfono omni-direccional de alta calidad configurable remotamente a través de la app rango de detección: 8m / angulo 120° sensibilidad: 2m;4m;6m;8m vidrio: groso', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDMCK-EG2-WB', 'Hikvision DS-PDMCK-EG2-WB 433mhz) contacto magnetico + vibración impacto - inlambrico contacto', 'Domótica', 27.00, '433mhz) contacto magnetico + vibración impacto - inlambrico contacto magnetico combinado con detección de impacto, vibración, golpes e inclinación extensión de 2 zonas cableadas detección de impacto: high, normal, low detección de inclniación: hasta 25° distancia apertura 43mm max entrada de alarma nc / no / impulse count indicador led: verde(mc),naranja(tilt),rojo(shock),azul(alarm', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDWL-E-WB', 'Hikvision DS-PDWL-E-WB 433mhz) detector de fuga de agua inalambrico diseño a prueba de agua', 'Domótica', 34.00, '433mhz) detector de fuga de agua inalambrico diseño a prueba de agua para multiples aplicaciones configurable remotamente a través de la app procesamiento digital antivandalismo indicador led rango rf de 1km', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDSMK-S-WB', 'Hikvision DS-PDSMK-S-WB 433mhz) detector de humo fotoelectrico inalambrico recamara de alta', 'Domótica', 39.00, '433mhz) detector de humo fotoelectrico inalambrico recamara de alta calidad con sensor fotoelectrico configurable remotamente a través de la app vida util de bateria de 10 años certificación en 14604 buzzer ≥ 85db @ 3 m rango rf de 800m', 'DISPONIBLE'),
  ('Hikvision', 'DS-PD452SMK-WB', 'Hikvision DS-PD452SMK-WB 433mhz) detector de humo, calor y monóxido de carbono (co) cámara de', 'Domótica', 66.00, '433mhz) detector de humo, calor y monóxido de carbono (co) cámara de alta calidad con sensor fotoeléctrico alarma si se supera la dosis acumulada de monóxido de carbono: 50 ppm (0,005 %) o más: en 90 minutos; 100 ppm (0,01 %) o más: en 40 minutos; 300 ppm (0,03 %) o más: en un máximo de 3 minutos alarma de temperatura constante: >64 °c alarma de temperatura diferencial: t >10 °c/min color: negro', 'DISPONIBLE'),
  ('Hikvision', 'DS-PKF1-WB', 'Hikvision DS-PKF1-WB 433mhz) control remoto (keyfob inalambrico) 4 botones de operación', 'Domótica', 22.00, '433mhz) control remoto (keyfob inalambrico) 4 botones de operación, distancia soportada 500 metros (area abierta), plastico + goma, indicador led 3 colores, 1 bateria 210mah (3v, cr2032) incluida', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDEB1-EG2-WB', 'Hikvision DS-PDEB1-EG2-WB 433mhz) boton de panico/emergencia inalambrico configurable remotamente', 'Domótica', 16.00, '433mhz) boton de panico/emergencia inalambrico configurable remotamente a través de la app 1 boton / indicador led antivandalismo rango rf de 800 metros', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDEBP1-EG2-WB', 'Hikvision DS-PDEBP1-EG2-WB 433mhz) boton de panico/emergencia inalambrico portatil configurable', 'Domótica', 16.00, '433mhz) boton de panico/emergencia inalambrico portatil configurable remotamente a través de la app 1 boton / indicador led intemeprie ip66 rango rf de 800 metros', 'DISPONIBLE'),
  ('Hikvision', 'DS-PS1-I-WB/Red', 'Hikvision DS-PS1-I-WB/Red 433mhz) sirena para interior inalambrica configurable remotamente a', 'Domótica', 38.00, '433mhz) sirena para interior inalambrica configurable remotamente a través de la app buzzer: 110db alarma de incendio, de panico y de intrusión rango rf de 900 metros', 'DISPONIBLE'),
  ('Hikvision', 'DS-PS1-E-WB/Blue', 'Hikvision DS-PS1-E-WB/Blue 433mhz) luz azul - no disponible sirena inalambrica con luz', 'Domótica', 25.00, '433mhz) luz azul - no disponible sirena inalambrica con luz estroboscopica intemperie ip65 decibeles/sónido: 110db indicador led para el estatus voltaje: 4 baterias 3v cr123a (incluidas) / fuente 12vcd 3 años de vida util de la batería antivandalismo frontal y trasero configurable remotamente a través de la app estatus control de acceso hikvision ds-pm1-o1l-wb (433mhz) contactor inalambrico switch inalambrico para control de reles ideal para dispositivos de bajo voltaje leds indicadores para est', 'DISPONIBLE'),
  ('Hikvision', 'DS-PM1-O1H-WB', 'Hikvision DS-PM1-O1H-WB 433mhz) contactor inalambrico switch inalambrico para control de reles', 'Domótica', 28.00, '433mhz) contactor inalambrico switch inalambrico para control de reles ideal para dispositivos de alto voltaje leds indicadores para estatus salida de rele: 1, no/nc (ac 100~240v, max 13a ）', 'DISPONIBLE'),
  ('Hikvision', 'DS-PDB-IN', 'Hikvision DS-PDB-IN - ceilingbracket base de sensor para instalación en techo dimensiones', 'Insumos', 1.25, '- ceilingbracket base de sensor para instalación en techo dimensiones 41 x 46 x 32 mm plastico abs color blanco', 'DISPONIBLE'),
  ('Hikvision', 'DS-KEB801X-C', 'Hikvision DS-KEB801X-C ESTACION DE ALARMA DE PANICO DE EMERGENCIA CON VIDEO Llamada de', 'Domótica', 599.00, 'ESTACION DE ALARMA DE PANICO DE EMERGENCIA CON VIDEO Llamada de emergencia con un solo toque Imágenes de alta calidad con cámara integrada de 4 MP Seguridad en tiempo real mediante detección de sonido y voz Compatible con transmisión Compatible con dos puertos de red Ranura SD integrada compatible con tarjetas MicroSD/SDHC/SDXC de hasta 256 GB Compatible con sirena y expansión de audio 2 entradas de alarma / 2 salidas de alarma 1 sirena; el sonido se puede configurar por separado 1 lámpara; la l', 'DISPONIBLE'),
  ('Hikvision', 'DS-1AC6APL1', 'Hikvision DS-1AC6APL1 6 HILOS - NO DISPONIBLE CABLE CABLE DE ALARMA LSZH BLINDADO DE 4 / 6', 'Insumos', 177.00, '6 HILOS - NO DISPONIBLE CABLE CABLE DE ALARMA LSZH BLINDADO DE 4 / 6 HILOS Ideal para edificios de oficinas de gran altura, hospitales, centros de entretenimiento, hoteles, pensiones y otros edificios. Se utiliza para el cableado de alarmas contra incendios, detectores de humo, comunicaciones de voz, alarmas antirrobo y circuitos de protección contra incendios. Conductor de cobre trenzado desnudo con menor resistencia, mejores propiedades eléctricas y mejor rendimiento de transmisión. Cubierta c', 'DISPONIBLE'),
  ('Hikvision', 'DS-1AC2B4APL1', 'Hikvision DS-1AC2B4APL1 2+4 hilos', 'Insumos', 220.00, '2+4 hilos', 'DISPONIBLE'),
  ('Hikvision', 'ISD-SMG1118L', 'Hikvision ISD-SMG1118L Arco detector de metal de 18 zonas precisión de detección: el metal', 'Domótica', 1590.00, 'Arco detector de metal de 18 zonas precisión de detección: el metal ferromagnético del tamaño de una moneda (d: 25 mm) es detectable en el centro del detector. se pueden excluir productos como hebilla de cinturón. cobre, aluminio y zinc (metal no ferromagnético de más de 150 g), cuchillo restringido y pistola son detectables detecta todos los objetos metálicos a más de 2 cm del suelo detecta objetos metalicos lanzados a través de la puerta detecta múltiples metales en diferentes posiciones del c', 'DISPONIBLE'),
  ('Hikvision', 'ISD-SMG218L', 'Hikvision ISD-SMG218L Arco detector de metal de 18 zonas arco detector de metales de 18 zonas', 'Domótica', 2095.00, 'Arco detector de metal de 18 zonas arco detector de metales de 18 zonas con pantalla lcd de 7" / conteo de personas y alarmas / ajuste de sensibilidad e interferencias / mejora anti- interferencia detección precisa de metales de 25 mm sensibilidad ajustable en 999 niveles pantalla lcd de 7" con información en tiempo real 18 zonas de detección programables simultáneas diseño modular para fácil mantenimiento y transporte conteo de personas con sensores ir bilaterales configuración remota a través ', 'DISPONIBLE'),
  ('Hikvision', 'NP-SH100', 'Hikvision NP-SH100 Detector de metales manual sensibilidad de detección ajsutable alta', 'Domótica', 50.00, 'Detector de metales manual sensibilidad de detección ajsutable alta velocidad de detección con gran area de snoda alarma de batería baja. indicador led batería cargando 2 modos de alarma: vibración y audible/visual a prueba de caída (protección contra caídas de 1 m', 'DISPONIBLE'),
  ('Hikvision', 'DS-TDSB0G-FK/60m', 'Hikvision DS-TDSB0G-FK/60m RADAR PERIMETRAL DE 60 METROS DE DISTANCIA Obtención de la distancia', 'Domótica', 1275.00, 'RADAR PERIMETRAL DE 60 METROS DE DISTANCIA Obtención de la distancia, la velocidad y el ángulo del objeto. Localización de objetivos y seguimiento de rastros. Bloqueo de objetivos múltiples y vinculación de videos multidimensionales. Modos multiescena seleccionables modo experto, modo abierto, modo arbusto. Sensibilidad configurable. Se vuelven a verificar los análisis de videos locales y se capturan imágenes para filtrar las falsas alarmas, como el balanceo de árboles y mascotas. Detección de 3', 'DISPONIBLE'),
  ('Hikvision', 'DS-TDSB0G-FK/120m', 'Hikvision DS-TDSB0G-FK/120m RADAR PERIMETRAL DE 120 METROS DE DISTANCIA Obtención de la distancia', 'Domótica', 1850.00, 'RADAR PERIMETRAL DE 120 METROS DE DISTANCIA Obtención de la distancia, la velocidad y el ángulo del objeto. Localización de objetivos y seguimiento de rastros. Bloqueo de objetivos múltiples y vinculación de videos multidimensionales. Modos multiescena seleccionables modo experto, modo abierto, modo arbusto. Sensibilidad configurable. Se vuelven a verificar los análisis de videos locales y se capturan imágenes para filtrar las falsas alarmas, como el balanceo de árboles y mascotas. Detección de ', 'DISPONIBLE'),
  ('Hikvision', 'DS-TDSB0G-FK/500m', 'Hikvision DS-TDSB0G-FK/500m RADAR PERIMETRAL DE 500 METROS DE DISTANCIA Obtención de la distancia', 'Domótica', 12950.00, 'RADAR PERIMETRAL DE 500 METROS DE DISTANCIA Obtención de la distancia, la velocidad y el ángulo del objeto. Localización de objetivos y seguimiento de rastros. Bloqueo de objetivos múltiples y vinculación de videos multidimensionales. Modos multiescena seleccionables modo experto, modo abierto, modo arbusto. Sensibilidad configurable. Se vuelven a verificar los análisis de videos locales y se capturan imágenes para filtrar las falsas alarmas, como el balanceo de árboles y mascotas. Detección de ', 'DISPONIBLE'),
  ('Hikvision', 'DS-PRB-1110', 'Hikvision DS-PRB-1110 SOPORTE DE PARED PARA RADAR Material: Metal. Dimensiones: 200 x 130 x', 'Insumos', 28.00, 'SOPORTE DE PARED PARA RADAR Material: Metal. Dimensiones: 200 x 130 x 115 mm. Peso: 800 gramos. Color: Blanco.', 'DISPONIBLE'),
  ('Hikvision', 'DS-PRB-1120', 'Hikvision DS-PRB-1120 SOPORTE AUXILIAR DE RADAR PARA PTZ Material: Aleación de aluminio', 'Insumos', 17.00, 'SOPORTE AUXILIAR DE RADAR PARA PTZ Material: Aleación de aluminio. Dimensiones: 96 x 56 mm. Peso: 220 gramos. Color: Blanco.', 'DISPONIBLE'),
  ('Hikvision', 'DS-PRB-1200', 'Hikvision DS-PRB-1200 SOPORTE DE POSTE PARA RADAR Material: Metal. Dimensiones: 120 x 130 x', 'Insumos', 47.00, 'SOPORTE DE POSTE PARA RADAR Material: Metal. Dimensiones: 120 x 130 x 85 mm. Peso: 1200 gramos. Color: Blanco.', 'DISPONIBLE'),
  ('Hikvision', 'DS-PRB-1310', 'Hikvision DS-PRB-1310 SOPORTE DE PARED / POSTE PARA RADAR Material: Metal. Dimensiones: 200 x', 'Insumos', 65.00, 'SOPORTE DE PARED / POSTE PARA RADAR Material: Metal. Dimensiones: 200 x 130 x 70 mm. Peso: 2000 gramos. Color: Blanco', 'DISPONIBLE'),
  ('Hikvision', 'DS-PRB-2200', 'Hikvision DS-PRB-2200 SOPORTE DE POSTE PARA RADAR Y PTZ Material: Metal. Dimensiones: 200 x', 'Insumos', 70.00, 'SOPORTE DE POSTE PARA RADAR Y PTZ Material: Metal. Dimensiones: 200 x 130 x 160 mm. Peso: 2100 gramos. Color: Blanco', 'DISPONIBLE'),
  ('Ubiquiti', 'UA-Reader', 'Ubiquiti UA-Reader Lite UniFi Access Reader Lite Un conveniente escáner de acceso a la', 'Network', 120.00, 'Lite UniFi Access Reader Lite Un conveniente escáner de acceso a la puerta compatible con el lector NFC y desbloqueo manual de la puerta. Instalación en interiores o bajo un voladizo de techo en el exterior. 1 entrada PoE alimentada por un concentrador de acceso Chip de seguridad que admite cifrado NFC avanzado Desbloqueo móvil con las aplicaciones móviles Access o UI Clasificación IP: IP54 Interfaz de red: 10/100 MbE / Método de alimentación: PoE Botón: 1 Restablecimiento de fábrica / LED: Blan', 'DISPONIBLE'),
  ('Ubiquiti', 'UA-Hub', 'Ubiquiti UA-Hub UniFi Access Hub Un mecanismo de puerta única que proporciona control', 'Network', 99.00, 'UniFi Access Hub Un mecanismo de puerta única que proporciona control completo de entrada y salida a través de lectores de acceso conectados. (2) Terminales de bloqueo (12 V y seco) (2) Terminales AUX para sirena externa y abridor de puerta automático (4) Entradas adicionales (sensores y botones) Conexión y alimentación mediante PoE++ Conéctese a dos lectores UniFi Access y una cámara UniFi Protect Interfaz de red (4) 1GbE Máx. consumo de energía 51W Terminales de entrada REX - request to exit R', 'DISPONIBLE'),
  ('Ubiquiti', 'UA-G2-SK-Pro', 'Ubiquiti UA-G2-SK-Pro Access G2 Starter Kit Pro Experiencia profesional para una puerta con', 'Network', 739.00, 'Access G2 Starter Kit Pro Experiencia profesional para una puerta con dos lectores. (1) Hub de puerta (1) Lector G2 Pro (1) Lector G2 para salida de puerta o entrada para una puerta adicional (se requiere un segundo Hub) (2) Llaveros de bolsillo Interfaz de red: (5) 10/100/1000 Base-T Método de alimentación: PoE++ Entrada PoE: 50 V CC, 1 A Salida PoE: PoE passthrough, (4) PoE, 50 V CC, total 20 W Entrada digital: Solicitud de salida/solicitud de entrada/liberación remota/sensor de posición de pu', 'DISPONIBLE'),
  ('Ubiquiti', 'UA-Intercom', 'Ubiquiti UA-Intercom UniFi Intercom Terminal de intercomunicación para interior y exterior', 'Domótica', 492.00, 'UniFi Intercom Terminal de intercomunicación para interior y exterior para gestionar solicitudes de entrada a edificios residenciales y comerciales. Desbloqueo mediante tarjeta NFC, aplicación móvil UniFi Identity, código PIN o código QR Directorio y timbre para solicitar la entrada Se empareja con varios visores de intercomunicación UniFi para control de acceso remoto Se conecta a la serie UniFi Access Hub mediante PoE Resistente a la intemperie (exposición al aire libre de -30 a 60 °C) Materia', 'DISPONIBLE'),
  ('Ubiquiti', 'UA-Intercom-Viewer', 'Ubiquiti UA-Intercom-Viewer Display de intercom Pantalla que funciona con Intercom y G2 Reader Pro', 'Domótica', 492.00, 'Display de intercom Pantalla que funciona con Intercom y G2 Reader Pro para detección de visitantes y control de acceso remoto. Recibe llamadas de timbre desde una o más ubicaciones Audio bidireccional Vista en vivo instantánea Pantalla táctil de 5" Tecnología de pantalla táctil: Multitáctil capacitiva Conexión y alimentación mediante un conmutador PoE Interfaz de red: (1) puerto RJ45 de 10/100 Mbps Método de alimentación: PoE Micrófono: Sí Altavoz: Sí', 'DISPONIBLE'),
  ('Ubiquiti', 'UVC-G4', 'Ubiquiti UVC-G4 Doorbell Pro PoE Kit Your premium UniFi doorbell with integrated PoE', 'Domótica', 575.00, 'Doorbell Pro PoE Kit Your premium UniFi doorbell with integrated PoE and included PoE chime for plug-and-play installation Intercomunicador UniFi premium con PoE integrado y timbre PoE incluido para instalación plug-and-play. HDR mejorado y rendimiento con poca luz Pantalla de bienvenida programable y cámara secundaria de detección de paquetes Detecciones de eventos de IA Conexión y alimentación mediante PoE Audio bidireccional integrado Incluye timbre PoE Resistente a la intemperie (cubierto al', 'DISPONIBLE');

update public.products p
set
  nombre = e.nombre,
  categoria = e.categoria,
  marca = e.marca,
  descripcion = e.descripcion,
  descripcion2 = 'Lista distribuidor 2026 · ' || e.estatus,
  costo = e.costo,
  precio = e.costo,
  utilidad = 0
from cat_acceso_2026 e
where lower(btrim(p.modelo)) = lower(btrim(e.modelo))
  and (
    p.marca is null
    or btrim(p.marca) = ''
    or lower(btrim(p.marca)) = lower(btrim(e.marca))
  );

insert into public.products (
  nombre, categoria, marca, modelo, descripcion, descripcion2,
  costo, precio, utilidad, cantidad
)
select
  e.nombre, e.categoria, e.marca, e.modelo, e.descripcion,
  'Lista distribuidor 2026 · ' || e.estatus,
  e.costo, e.costo, 0, 0
from cat_acceso_2026 e
where not exists (
  select 1
  from public.products p
  where lower(btrim(p.modelo)) = lower(btrim(e.modelo))
    and (
      p.marca is null
      or btrim(p.marca) = ''
      or lower(btrim(p.marca)) = lower(btrim(e.marca))
    )
);

commit;

select marca, count(*) as n
from public.products
where lower(btrim(coalesce(marca, ''))) in ('hikvision', 'hikfire', 'ubiquiti', 'omegasat')
group by 1
order by 1;

