begin;

drop table if exists cat_acceso_2026;
create temporary table cat_acceso_2026 (
  marca text not null,
  modelo text not null,
  nombre text not null,
  categoria text not null,
  costo numeric(14,2) not null,
  descripcion text,
  estatus text not null,
  primary key (marca, modelo)
);

insert into cat_acceso_2026 (marca, modelo, nombre, categoria, costo, descripcion, estatus)
values
  ('Hikvision', 'DS-K2210', 'Hikvision DS-K2210 CONTROLADOR MAESTRO PARA ASCENSOR 128 PISOS Control de Acceso para los', 'Domótica', 270.00, 'CONTROLADOR MAESTRO PARA ASCENSOR 128 PISOS Control de Acceso para los pisos por huella, tarjeta o rostro 1 Botón de Pánico, 1 Botón de Incnedio, 1 Botón de Mantenimiento Funciones de Watchdog y Anti Vandalismo COMUNICACIÓN: TCP/IP, RS-485, Wiegand SALIDAS DE RELE: 5 20,000 TARJETAS Y 50,000 EVENTOS', 'DISPONIBLE'),
  ('Hikvision', 'DS-K2M0016A', 'Hikvision DS-K2M0016A Distribuidor esclavo para controlador de ascensor comunicación: rs-485', 'Domótica', 350.00, 'Distribuidor esclavo para controlador de ascensor comunicación: rs-485 con controlador maestro. dip switch para direccionamiento rs485. salidas de rele: 16 (para 16 pisos, 1 por piso) entradas de alarma: 2', 'DISPONIBLE'),
  ('Hikvision', 'WG-PRINT-58HW-USB', 'Hikvision WG-PRINT-58HW-USB Impresora térmica de tickets para visitantes uso con terminal de', 'Domótica', 120.00, 'Impresora térmica de tickets para visitantes uso con terminal de visitantes ds-k5032-d. el ancho del papel es 57 ± 0,5 mm (2,3” ± 0,02”). la resolución es de 203 ppp. rendimiento estable, impresión clara. material industrial para una mejor capacidad de ataque. está disponible la impresión continua durante mucho tiempo. la velocidad de impresión es de 90 mm/s. soporta interfaz usb', 'DISPONIBLE'),
  ('Hikvision', 'DS-TRI900-1/A', 'Hikvision DS-TRI900-1/A Lector de tarjetas uhf (tag) largo alcance compatible con epc c1', 'Domótica', 435.00, 'Lector de tarjetas uhf (tag) largo alcance compatible con epc c1 gen2/iso 18000-6c. compatible con el modo de lectura intensiva de epc. lectura a larga distancia, potencia de salida de rf de hasta 33 dbm. admite una velocidad de lectura de datos de etiquetas de 640 kbps. admite comunicación ethernet y wiegand. configuración y parametrización flexibles para maximizar la lectura de etiquetas y un rendimiento óptimo. frecuencia de trabajo: 840~960mhz (opcional). antena polarizada circularmente de 9', 'DISPONIBLE'),
  ('Hikvision', 'DS-TRD902-1/A', 'Hikvision DS-TRD902-1/A Emisor / enrolador de tarjetas uhf cumple con el estándar de protocolo', 'Domótica', 2.50, 'Emisor / enrolador de tarjetas uhf cumple con el estándar de protocolo epc c1 gen2/iso18000-6c. buen mecanismo anticolisión, múltiples etiquetas electrónicas al mismo tiempo. fuente de alimentación e indicación de estado de funcionamiento. 1 interfaz usb. frecuencia de funcionamiento: predeterminada 920,5 mhz ~ 924,5 mhz. potencia de transmisión: 10 dbm. antena polarizada circularmente de 3 dbi. distancia de lectura: ≤30 cm a impinj h47, según el tipo de etiqueta y la potencia de 295.00 disponib', 'DISPONIBLE'),
  ('Hikvision', 'DS-K3G200LX-R/Dm55', 'Hikvision DS-K3G200LX-R/Dm55 TORNIQUETE TIPO TRIPODE Acero inoxidable SUS304 resistente. 2 Botones', 'Domótica', 735.00, 'TORNIQUETE TIPO TRIPODE Acero inoxidable SUS304 resistente. 2 Botones de Salida. 1 Entrada de Alarma de Incendio. Compatible con Controles de Acceso de otras marcas. Paso de más de 25 personas por minuto. Canal de 550mm de ancho, Voltaje 110~230VAC, Dimensiones: 426 mm ×268 mm × 982.5 mm. Soporta Terminal de Reconocimiento Facial (No incluida', 'DISPONIBLE'),
  ('Hikvision', 'DS-K3G200LX-R/Pg', 'Hikvision DS-K3G200LX-R/Pg - Dm55 TORNIQUETE TIPO TRIPODE Acero inoxidable SUS304 resistente. 2', 'Domótica', 760.00, '- Dm55 TORNIQUETE TIPO TRIPODE Acero inoxidable SUS304 resistente. 2 Botones de Salida. 1 Entrada de Alarma de Incendio. Compatible con Controles de Acceso de otras marcas. Paso de más de 25 personas por minuto. Canal de 550mm de ancho, Voltaje 110~230VAC, Dimensiones: 426 mm ×268 mm × 982.5 mm. Soporta Terminal de Reconocimiento Facial (No incluida', 'DISPONIBLE'),
  ('Hikvision', 'DS-K3G301LX-R/Dm55', 'Hikvision DS-K3G301LX-R/Dm55 Torniquete tipo tripode bidireccional carril bidireccional', 'Domótica', 750.00, 'Torniquete tipo tripode bidireccional carril bidireccional (entrada/salida) el led indica el estado de entrada/salida y paso. paso de la alarma de incendio configuraciones de duración de paso válida rendimiento: 25 a 60 personas por minuto interfaces: 2 botones de salida y 1 entrada de alarma fuente de alimentación: 100 a 240 vca; 50 a 60 hz dimensiones: 1200mm × 233mm × 1000mm (47.2" × 9.2" × 39.4") ancho de carril: 550 mm compatible con cualquier sistema de contacto seco', 'DISPONIBLE'),
  ('Hikvision', 'DS-K3G301LX-R/Pg', 'Hikvision DS-K3G301LX-R/Pg - dm55 torniquete tipo tripode bidireccional carril bidireccional', 'Domótica', 760.00, '- dm55 torniquete tipo tripode bidireccional carril bidireccional (entrada/salida) el led indica el estado de entrada/salida y paso. paso de la alarma de incendio configuraciones de duración de paso válida rendimiento: 25 a 60 personas por minuto interfaces: 2 botones de salida y 1 entrada de alarma fuente de alimentación: 100 a 240 vca; 50 a 60 hz dimensiones: 1200mm × 233mm × 1000mm (47.2" × 9.2" × 39.4") ancho de carril: 550 mm compatible con cualquier sistema de contacto seco incluye orifici', 'DISPONIBLE'),
  ('Hikvision', 'DS-K3B220LX-R/Pg', 'Hikvision DS-K3B220LX-R/Pg - Dp65 Lado Derecho TORNIQUETE TIPO BARRERA (SWING BARRIER) DERECHA 4', 'Domótica', 1725.00, '- Dp65 Lado Derecho TORNIQUETE TIPO BARRERA (SWING BARRIER) DERECHA 4 pares de detectores de luz IR: Validación de permisos y anti- tailgating, Luz LED que indica dirección de paso, Configuracipon de tiempo válido de paso, Apertura de emergencia en caso de incendio, Motor sin escobillas, 2 botones de salida, 1 entada de alarma, Paso de 20 a 60 personas/minuto, Canal de 650mm, Material acero inoxidable SUS304 y puertas de vídrio acrilico, Dimensiones: 1205mm (47.44'''') × 146mm (5.75'''') × 1000mm (3', 'DISPONIBLE'),
  ('Hikvision', 'DS-K3B220LX-M/Pg', 'Hikvision DS-K3B220LX-M/Pg - Dp90 Centro TORNIQUETE TIPO BARRERA - MEDIO 4 pares de detectores de', 'Domótica', 990.00, '- Dp90 Centro TORNIQUETE TIPO BARRERA - MEDIO 4 pares de detectores de luz IR: Validación de permisos y anti- tailgating, Luz LED que indica dirección de paso, Configuracipon de tiempo válido de paso, Apertura de emergencia en caso de incendio, Motor sin escobillas, 2 botones de salida, 1 entada de alarma, Paso de 20 a 60 personas/minuto, Canal de 900mm, Material acero inoxidable SUS304 y puertas de vídrio acrilico, Dimensiones: 1205mm (47.44'''') × 146mm (5.75'''') × 1000mm (39.37''''). No incluye le', 'DISPONIBLE'),
  ('Hikvision', 'DS-K3B411BX-R/M', 'Hikvision DS-K3B411BX-R/M - Dp65 Lado Derecho TORNIQUETE TIPO BARRERA ABATIBLE (SWING BARRIER) 6', 'Domótica', 1415.00, '- Dp65 Lado Derecho TORNIQUETE TIPO BARRERA ABATIBLE (SWING BARRIER) 6 pares de detectores de luz infrarroja: Validación de permisos y prevención de acceso no autorizado. Un indicador LED muestra la dirección de paso. La barrera dejará de funcionar durante un tiempo si detecta una obstrucción al abrirse o cerrarse. Autodetección, autodiagnóstico y alarma automática. El sistema cancelará el permiso de paso si una persona no atraviesa el carril dentro del tiempo permitido. La puerta permanece abie', 'DISPONIBLE'),
  ('Hikvision', 'DS-K3B501SX-L/MPg', 'Hikvision DS-K3B501SX-L/MPg - Dm65 Lado Izquierdo TORNIQUETE TIPO BARRERA ABATIBLE (SWING BARRIER)', 'Domótica', 1690.00, '- Dm65 Lado Izquierdo TORNIQUETE TIPO BARRERA ABATIBLE (SWING BARRIER) 12 pares de detectores de luz IR: Validación de permisos y anti- tailgating, Luz LED que indica dirección de paso, Alarma audible y visual cuando detecte una obstrucción al abrir/cerrar la barrera. Autodetección, Autodiagnóstico y alarma automática. Configuración de la duración válida de adelantamiento. La puerta permanece abierta cuando se activa la alarma de incendio. La barrera está en estado libre cuando se apaga. Ancho d', 'DISPONIBLE'),
  ('Hikvision', 'DS-K3B501SX-M/MPg', 'Hikvision DS-K3B501SX-M/MPg - Dm65 Centro TORNIQUETE TIPO BARRERA ABATIBLE (SWING BARRIER) 12 pares', 'Domótica', 1690.00, '- Dm65 Centro TORNIQUETE TIPO BARRERA ABATIBLE (SWING BARRIER) 12 pares de detectores de luz IR: Validación de permisos y anti- tailgating, Luz LED que indica dirección de paso, Alarma audible y visual cuando detecte una obstrucción al abrir/cerrar la barrera. Autodetección, Autodiagnóstico y alarma automática. Configuración de la duración válida de adelantamiento. La puerta permanece abierta cuando se activa la alarma de incendio. La barrera está en estado libre cuando se apaga. Ancho del Canal', 'DISPONIBLE'),
  ('Hikvision', 'DS-K6B961TDQLX', 'Hikvision DS-K6B961TDQLX - L/Dp90 Lado Izquierdo 5,999.00 DISPONIBLE TORNIQUETE INTELIGENTE', 'Domótica', 9499.00, '- L/Dp90 Lado Izquierdo 5,999.00 DISPONIBLE TORNIQUETE INTELIGENTE ABATIBLE DE LA SERIE ULTRA Pantalla de 6,95 pulgadas y módulo de reconocimiento facial integrado. Compatible con configuración web para PC y dispositivos móviles, y autodiagnóstico para mantenimiento. Función de modo AP para teléfonos móviles (Android) para acceder más fácilmente con un simple toque a través de la etiqueta NFC. Conexión de incendios: Al activarse la señal de incendio, la barrera se abre automáticamente para evacu', 'DISPONIBLE'),
  ('Hikvision', 'DS-K6B961TEQLX', 'Hikvision DS-K6B961TEQLX - R/Dp90 Lado Derecho', 'Domótica', 5999.00, '- R/Dp90 Lado Derecho', 'DISPONIBLE'),
  ('Hikvision', 'DS-K6B961TDQLX-2', 'Hikvision DS-K6B961TDQLX-2 - M/Dp90-65 Lado Centro 90 cm / 65 cm TORNIQUETE INTELIGENTE ABATIBLE', 'Domótica', 9499.00, '- M/Dp90-65 Lado Centro 90 cm / 65 cm TORNIQUETE INTELIGENTE ABATIBLE DE LA SERIE ULTRA Pantalla de 6,95 pulgadas y módulo de reconocimiento facial integrado. Compatible con configuración web para PC y dispositivos móviles, y autodiagnóstico para mantenimiento. Función de modo AP para teléfonos móviles (Android) para acceder más fácilmente con un simple toque a través de la etiqueta NFC. Conexión de incendios: Al activarse la señal de incendio, la barrera se abre automáticamente para evacuación ', 'DISPONIBLE'),
  ('Hikvision', 'DS-K7R83X', 'Hikvision DS-K7R83X PANEL DE CONTROL REMOTO PARA TORNIQUETES Y BARRERAS Pantalla táctil IPS', 'Domótica', 275.00, 'PANEL DE CONTROL REMOTO PARA TORNIQUETES Y BARRERAS Pantalla táctil IPS de 7 pulgadas con resolución de 1024 × 600. Autodefine la función del botón de la llave. Úselo en mostradores de recepción o salas de seguridad, fácil de controlar a distancia. Económico en comparación con los llaveros tradicionales. Protocolo de comunicación: TCP/IP. Wi-Fi 802.11 b/g/n. Configuración mediante navegador web. Videoportero: No compatible. Alimentación: IEEE802.3af, PoE estándar / 12 VCC/1 A. Controle el estado', 'DISPONIBLE'),
  ('Hikvision', 'Q340-HK', 'Hikvision Q340-HK Lector de código qr - especial para torniquetes y barreras lector de', 'Domótica', 150.00, 'Lector de código qr - especial para torniquetes y barreras lector de proximidad rfid. intemperie ip67, comunicación wiegand.', 'DISPONIBLE'),
  ('Hikvision', 'DS-KAB-COVER', 'Hikvision DS-KAB-COVER TAPA DE PLASTICO Tapa del orificio de instalación del reconocimiento', 'Domótica', 20.00, 'TAPA DE PLASTICO Tapa del orificio de instalación del reconocimiento facial del torniquete. Dimensiones: 115 mm × 115 mm × 18 mm (4.53" × 4.53" × 0.71"', 'DISPONIBLE'),
  ('Hikvision', 'DS-KAB-601COVER', 'Hikvision DS-KAB-601COVER TAPA DE ACERO INOXIDABLE Tapa del orificio de instalación del', 'Domótica', 45.00, 'TAPA DE ACERO INOXIDABLE Tapa del orificio de instalación del reconocimiento facial del torniquete. Dimensiones: 115 mm × 115 mm × 18 mm (4.53" × 4.53" × 0.71"', 'DISPONIBLE'),
  ('Hikvision', 'DS-KAB6-ZU1', 'Hikvision DS-KAB6-ZU1 SOPORTE PARA TERMINALES DE RECONOCIMIENTO FACIAL Disponible para', 'Domótica', 365.00, 'SOPORTE PARA TERMINALES DE RECONOCIMIENTO FACIAL Disponible para terminal de reconocimiento facial de cualquier marca que admite la instalación de cajas de conexiones en puertas rápidas y torniquetes. Diseño Estético. Compatible con Terminales Faciales y Térmicas. Dimensions 100 mm × 100 mm × 196 mm. Material: aleación de aluminio AL-6061. Uso en interior y exterior - NO DISPONIBLE ESTATUS CONTROL DE ACCESO HIKVISION DS-K3GL606WX-WB MOTOR DE PORTON CORREDIZO 600 KG Compatible con interfaces WIFI', 'DISPONIBLE'),
  ('Hikvision', 'DS-TMG300-DR/A', 'Hikvision DS-TMG300-DR/A Brazo iluminado de 3m BARRERA VEHICULAR CON BRAZO ILUMINADO DE 3 MTS', 'Domótica', 895.00, 'Brazo iluminado de 3m BARRERA VEHICULAR CON BRAZO ILUMINADO DE 3 MTS Barrera Vehicular derecja. Brazo Iluminado Rojo/Verde de 3 mts Incluido. 3 Seg para Apertura. Cierre Automático con Tiempo Configurable. 2,500,000 MCBF. Compatible con Cualquier Control de Acceso. Motor brushless DC silencioso. Reapertura automática ante impacto vehicular. Compatible con sistemas múltiples anti-golpes. Apertura manual al perder energía. Cuenta con 2 controles. Reapertura en caso de golpe a vehiculo. Compatible ', 'DISPONIBLE'),
  ('Hikvision', 'DS-TMG301-DR(2+2)', 'Hikvision DS-TMG301-DR(2+2) Brazo articulado de 4m BARRERA VEHICULAR CON BRAZO ILUMINADO DE 3 MTS', 'Domótica', 750.00, 'Brazo articulado de 4m BARRERA VEHICULAR CON BRAZO ILUMINADO DE 3 MTS Fácil instalación lateral con estructura compacta. Incorpora un pequeño motor de CC sin escobillas y bajo nivel de ruido para aumentar el par de salida y lograr un control inteligente y preciso. Admite múltiples modos anticaída, como infrarrojos, detectores de vehículos y radares. Velocidad de ascenso: de 3 a 6 s. Velocidad de descenso: de 3 a 6 s. Dirección de la brazo: izquierda/derecha. Tipo de pluma compatible: pluma plega', 'DISPONIBLE'),
  ('Hikvision', 'DS-TMG001-5', 'Hikvision DS-TMG001-5 3m octagonal) BRAZO RECTO DE REPUESTO PARA BARRERAS HIKVISION Reemplazo', 'Insumos', 175.00, '3m octagonal) BRAZO RECTO DE REPUESTO PARA BARRERAS HIKVISION Reemplazo de brazo de barrera de 3 metros Brazo fabrciado en Aluminio No cuenta con Tornilleria Dimensiones: 3000 × 100 × 45 mm (118.1 × 3.9 × 1.8 inch) Peso: 3.07 kg (6.8 lb', 'DISPONIBLE'),
  ('Hikvision', 'DS-TMG004-5', 'Hikvision DS-TMG004-5 4m) BRAZO TIPO CERCA DE REPUESTO PARA BARRERAS HIKVISION Dimensiones', 'Insumos', 345.00, '4m) BRAZO TIPO CERCA DE REPUESTO PARA BARRERAS HIKVISION Dimensiones del mástil: 4000 × 970 × 96 mm (157,5 × 38,2 × 3,8 pulgadas) Dimensiones del mástil (con embalaje): 4050 × 1020 × 130 mm (159,4 × 40,2 × 5,1 pulgadas) Material del mástil: Perfil de aluminio Peso del mástil (con embalaje): 9,6 kg (21,16 lb', 'DISPONIBLE'),
  ('Hikvision', 'DS-TMT201-D', 'Hikvision DS-TMT201-D ESTACIÓN DE TICKETS DE ENTRADA DE ESTACIONAMIENTO Pantalla LCD de alto', 'Domótica', 2450.00, 'ESTACIÓN DE TICKETS DE ENTRADA DE ESTACIONAMIENTO Pantalla LCD de alto brillo y temperatura de 10,1 pulgadas de ancho, texto de soporte, código bidimensional y otra visualización de información, imagen de soporte, reproducción en bucle de vídeo Lector de tarjetas IC integrado en el dispositivo, admite carga de tarjetas El dispositivo contiene 1 interfaz de salida de relé, que se puede utilizar para barrera de control remoto Admite la función de intercomunicación de voz en tiempo real, tecnología', 'DISPONIBLE'),
  ('Hikvision', 'DS-TMG035', 'Hikvision DS-TMG035 Anti Fall Radar', 'Domótica', 185.00, 'Anti Fall Radar', 'DISPONIBLE'),
  ('Hikvision', 'DS-TMG035-2', 'Hikvision DS-TMG035-2 Trigger Radar', 'Domótica', 210.00, 'Trigger Radar', 'DISPONIBLE'),
  ('Hikvision', 'DS-TPE104', 'Hikvision DS-TPE104 TERMINAL DE CONTROL DE GESTIÓN PARA ENTRADA Y SALIDA DE', 'Domótica', 1250.00, 'TERMINAL DE CONTROL DE GESTIÓN PARA ENTRADA Y SALIDA DE ESTACIONAMIENTOS Diseño sin ventilador, pero posee buen efecto de enfriamiento. Aluminio Negro. Temperatura de trabajo: 20 °C to 70 °C. Interfaz RS-232 estándar. 2 interfaces RS-485. 4 puertos USB 3.0. Sistema Operativo Windows. 5 Puertos Ethernet 10/100. 1 Puertos Ethernet 10/100/1000. Disco duro 2TB integrado de nivel de vigilancia de 3,5", que admite almacenamiento de imágenes y vídeos de gran capacidad. Equipado con una interfaz de audi', 'DISPONIBLE'),
  ('Hikvision', 'DS-TCG405-E', 'Hikvision DS-TCG405-E Camara unidad de video de entrada inteligente con reconocimiento y', 'Cámaras IP', 675.00, 'Camara unidad de video de entrada inteligente con reconocimiento y captura de placas vehículares anpr camara ip 4mp para utilizar con barreras vehiculares. lente varifocal motorizado 3.1-6mm, intemperie ip67 antivandlica ik10, leds de alto rendimiento (luz blanca e ir), soporta paso rapido de multiples vehículos, 12vdc o poe (802.3af), tarjeta tf hasta 128gb, reconoce placas sucias, salida de rele para barrera vehicular, lista blanca de hasta 30,000 vehículos 755.00 disponible sensor (radar) con', 'DISPONIBLE'),
  ('Hikvision', 'DS-KIS202T', 'Hikvision DS-KIS202T Puerta DS-KB2411-IM Monitor DS-KH2220 KIT DE VIDEO PORTERO ANALÓGICO', 'Domótica', 105.00, 'Puerta DS-KB2411-IM Monitor DS-KH2220 KIT DE VIDEO PORTERO ANALÓGICO MONITOR: Pantalla LCD a Color de 7", Audio IN/OUT, Micrófono y Altavoz integrados, soporta 1 cámara analógica adicional ESTACIÓN DE PUERTA: Resolución 720×576 @25fps, Micrófono y Altavoz, 2m de IR, Audio IN/OUT, 1 Salida de Relé', 'DISPONIBLE'),
  ('Hikvision', 'DS-KIS203T', 'Hikvision DS-KIS203T Puerta DS-KB2421-IM Monitor DS-KH2220 KIT DE VIDEO PORTERO ANALÓGICO', 'Domótica', 120.00, 'Puerta DS-KB2421-IM Monitor DS-KH2220 KIT DE VIDEO PORTERO ANALÓGICO MONITOR: Pantalla LCD a Color de 7", Audio IN/OUT, Micrófono y Altavoz integrados, soporta 1 cámara analógica adicional ESTACIÓN DE PUERTA: Resolución 720×576@25fps, Micrófono y Altavoz, 2m de IR, Audio IN/OUT, 1 Salida de Relé, Intemperie IP65', 'DISPONIBLE'),
  ('Hikvision', 'DS-KIS302-P', 'Hikvision DS-KIS302-P Puerta DS-KB2421-IM Monitor DS-KH6320-WTE1 KIT DE VIDEO PORTERO HIBRIDO', 'Domótica', 145.00, 'Puerta DS-KB2421-IM Monitor DS-KH6320-WTE1 KIT DE VIDEO PORTERO HIBRIDO (ANALOGICO / IP 4 HILOS) MONITOR: Pantalla LCD a Color de 7" Tactil, Audio IN/OUT, Micrófono y Altavoz integrados, Conexión a Internet por Cable o WiFi y por 4 Hilos al Frente de Calle. Memoria SD. Entrada y Salida de Alarma ESTACIÓN DE PUERTA: Resolución 1920 x 1080, Micrófono y Altavoz, 2m de IR, Audio IN/OUT, 1 Salida de Relé, Intemperie, Interface 4 Hilos', 'DISPONIBLE'),
  ('Hikvision', 'DS-KIS103', 'Hikvision DS-KIS103 Puerta DS-KB2421-IM Monitor DS-KH6320-WTE1 KIT DE VIDEO PORTERO', 'Domótica', 35.00, 'Puerta DS-KB2421-IM Monitor DS-KH6320-WTE1 KIT DE VIDEO PORTERO ANALOGICO DE 2 HILOS Apertura de 2 Puertas. Diferentes Tonos y Volúmenes de Timbre. Protección IP55. Kit de audio analógico plug & play de 2 cables. Diseño de llamada con un solo toque para facilitar las llamadas. Carcasa de aleación de aluminio con protección contra la lluvia. Permite ajustar el volumen del timbre, cambiar y seleccionar el tono de llamada. Compatible con desbloqueo remoto.', 'DISPONIBLE'),
  ('Hikvision', 'DS-KH2220', 'Hikvision DS-KH2220 MONITOR PARA VIDEO PORTERO ANALÓGICO Pantalla LCD a Color de 7", 4', 'Domótica', 55.00, 'MONITOR PARA VIDEO PORTERO ANALÓGICO Pantalla LCD a Color de 7", 4 Cables, permite comunicación es cascada, Audio IN/OUT, Micrófono y Altavoz integrados, soporta 1 cámara analógica adicional, 12V 5W. Compatible con DS-KB2421T-IM', 'DISPONIBLE'),
  ('Hikvision', 'DS-KIS212', 'Hikvision DS-KIS212 Puerta DS-KB2412T-IM Monitor DS-KH2230T KIT DE VIDEO PORTERO 4 HILOS HD', 'Domótica', 105.00, 'Puerta DS-KB2412T-IM Monitor DS-KH2230T KIT DE VIDEO PORTERO 4 HILOS HD MONITOR: Pantalla LCD a Color de 7", Audio IN/OUT, Micrófono y Altavoz integrados, Ethernet, Wifi, 2 Alarma IN ESTACIÓN DE PUERTA: Resolución 1280x720 @60fps, Micrófono y Altavoz, 2m de IR, Audio IN/OUT, 1 Salida de Relé, Lector IC, contacto magnetico, 4 Entradas 1 Salida, Metal, Intemperie IP65', 'DISPONIBLE'),
  ('Hikvision', 'DS-KIS213', 'Hikvision DS-KIS213 Puerta DS-KB2422T-IM Monitor DS-KH2230T KIT DE VIDEO PORTERO 4 HILOS HD', 'Domótica', 105.00, 'Puerta DS-KB2422T-IM Monitor DS-KH2230T KIT DE VIDEO PORTERO 4 HILOS HD MONITOR: Pantalla LCD a Color de 7", Audio IN/OUT, Micrófono y Altavoz integrados, Ethernet, Wifi, 2 Alarma IN ESTACIÓN DE PUERTA: Resolución 1280x720 @60fps, Micrófono y Altavoz, 2m de IR, Audio IN/OUT, 1 Salida de Relé, Lector IC, contacto magnetico, 4 Entradas 1 Salida, Metal, Intemperie IP65, IK08', 'DISPONIBLE'),
  ('Hikvision', 'DS-KIS213-P', 'Hikvision DS-KIS213-P Puerta DS-KB2422T-IM Monitor DS-KH2230T KIT DE VIDEO PORTERO 4 HILOS HD', 'Domótica', 140.00, 'Puerta DS-KB2422T-IM Monitor DS-KH2230T KIT DE VIDEO PORTERO 4 HILOS HD MONITOR: Pantalla LCD a Color de 7", Audio IN/OUT, Micrófono y Altavoz integrados, Ethernet, Wifi, 2 Alarma IN ESTACIÓN DE PUERTA: Resolución 1280x720 @60fps, Micrófono y Altavoz, 2m de IR, Audio IN/OUT, 1 Salida de Relé, Lector IC, contacto magnetico, 4 Entradas 1 Salida, Metal, Intemperie IP65, IK08', 'DISPONIBLE'),
  ('Hikvision', 'DS-KIS312-P', 'Hikvision DS-KIS312-P Puerta DS-KB2412T-IM Monitor DS-KH6352- WTDE6 KIT DE VIDEO PORTERO 4', 'Domótica', 135.00, 'Puerta DS-KB2412T-IM Monitor DS-KH6352- WTDE6 KIT DE VIDEO PORTERO 4 HILOS HD MONITOR: Pantalla LCD tactil a Color de 7", Audio IN/OUT, Micrófono y Altavoz integrados, Ethernet, Wifi, 2 Alarma IN, HIK-CONNECT ESTACIÓN DE PUERTA: Resolución 1280x720 @60fps, Micrófono y Altavoz, 2m de IR, Audio IN/OUT, 1 Salida de Relé, Lector IC, contacto magnetico, 4 Entradas 1 Salida, Metal, Intemperie IP65', 'DISPONIBLE'),
  ('Hikvision', 'DS-KIS313-P', 'Hikvision DS-KIS313-P Puerta DS-KB2412T-IM Monitor DS-KH2230T KIT DE VIDEO PORTERO 4 HILOS HD', 'Domótica', 150.00, 'Puerta DS-KB2412T-IM Monitor DS-KH2230T KIT DE VIDEO PORTERO 4 HILOS HD MONITOR: Pantalla LCD tactil a Color de 7", Audio IN/OUT, Micrófono y Altavoz integrados, Ethernet, Wifi, 2 Alarma IN, HIK-CONNECT ESTACIÓN DE PUERTA: Resolución 1280x720 @60fps, Micrófono y Altavoz, 2m de IR, Audio IN/OUT, 1 Salida de Relé, Lector IC, contacto magnetico, 4 Entradas 1 Salida, Metal, Intemperie IP65, IK08', 'DISPONIBLE'),
  ('Hikvision', 'DS-KIS602', 'Hikvision DS-KIS602 Puerta DS-KD8003-IME1 Monitor DS-KH6320-WTE1 Switch 4 Puertos PoE', 'Domótica', 235.00, 'Puerta DS-KD8003-IME1 Monitor DS-KH6320-WTE1 Switch 4 Puertos PoE Tarjeta TF 16GB KIT DE VIDEO PORTERO IP 2MP + SWITCH + TARJETA 16GB MONITOR: Pantalla LCD Táctil a Color de 7", 1024 × 600, Audio IN/OUT, Micrófono y Altavoz integrados, Ethernet, Wifi, 8 Alarma IN, 2 Salidas Relé, HIK-CONNECT ESTACIÓN DE PUERTA: Resolución HD 2MP, 96°, Micrófono y Altavoz, 2m de IR, Audio IN/OUT, 1 Salida de Relé, Lector IC, contacto magnetico, 4 Entradas 1 Salida, Metal, Intemperie IP65', 'DISPONIBLE'),
  ('Hikvision', 'DS-KIS604-P(B)', 'Hikvision DS-KIS604-P(B) Puerta DS-KV8113-WME1 Monitor DS-KH6320-WTE1 KIT DE VIDEO PORTERO IP', 'Domótica', 200.00, 'Puerta DS-KV8113-WME1 Monitor DS-KH6320-WTE1 KIT DE VIDEO PORTERO IP 2MP Wi-Fi MONITOR: Pantalla LCD a Color de 7" Táctil 1024 × 600, Micrófono y Altavoz integrados, Ethernet, Wifi, Micro SD 32G, PoE estándar, 8 Alarma IN, 2 Salidas de Relé ESTACIÓN DE PUERTA: Resolución 1280x720 @25fps WDR, Micrófono y Altavoz, 3m de IR, Audio IN/OUT, 1 Salidas de Relé, WiFi, Protección IK08 e Intemperie IP65, PoE estándar', 'DISPONIBLE'),
  ('Hikvision', 'DS-KIS603-P(B)', 'Hikvision DS-KIS603-P(B) Puerta DS-KV6113-WPE1 Monitor DS-KH6320-WTE1 PSU x 2 KIT DE VIDEO', 'Domótica', 200.00, 'Puerta DS-KV6113-WPE1 Monitor DS-KH6320-WTE1 PSU x 2 KIT DE VIDEO PORTERO IP 2MP Wi-Fi MONITOR: Pantalla LCD a Color de 7" Táctil 1024 × 600, Micrófono y Altavoz integrados, Ethernet, Wifi, Micro SD 32G, PoE estándar, 8 Alarma IN, 2 Salidas de Relé ESTACIÓN DE PUERTA: Resolución 1280x720 @25fps WDR, 3m de IR, Micrófono y Altavoz, Audio IN/OUT, 1 Salidas de Relé, 4 Alarma IN, WiFi, Intemperie IP65, PoE estándar, Detección Movimiento', 'DISPONIBLE'),
  ('Hikvision', 'DS-KIS606-P', 'Hikvision DS-KIS606-P Puerta DS-KV6113-PE1(C) Monitor DS-KH6110-WE1 Base DS-KABV6113-RS 2', 'Domótica', 195.00, 'Puerta DS-KV6113-PE1(C) Monitor DS-KH6110-WE1 Base DS-KABV6113-RS 2 fuentes de alimentación KIT DE VIDEO PORTERO IP 2MP MONITOR: Pantalla LCD a Color de 4.3" 480 × 272, Micrófono y Altavoz integrados, Ethernet, Cableada RJ45 PoE Estandar, 4 entradas alarma ESTACIÓN DE PUERTA: Resolución IP 2MP, Micrófono y Altavoz, 1 Salidas de Relé, 4 entradas alarma, 1 tamper, 1 boton de salida, 1 RS- 485, Intemperie IP65, PoE estándar, Detección Movimiento', 'DISPONIBLE'),
  ('Hikvision', 'DS-KH6000-E1', 'Hikvision DS-KH6000-E1 ESTACIÓN INTERIOR IP DE BAJO COSTO SIN PANTALLA Estación interior', 'Domótica', 45.00, 'ESTACIÓN INTERIOR IP DE BAJO COSTO SIN PANTALLA Estación interior económica sin pantalla. Fuente de alimentación PoE estándar sin adaptador de corriente adicional. Conveniente para que los usuarios personalicen funciones según sus propios hábitos de uso mediante 4 botones táctiles personalizados. Sin WiFi.', 'DISPONIBLE'),
  ('Hikvision', 'DS-KH6100-E1', 'Hikvision DS-KH6100-E1 ESTACIÓN INTERIOR IP DE BAJO COSTO CON PANTALLA Pantalla no táctil de', 'Domótica', 60.00, 'ESTACIÓN INTERIOR IP DE BAJO COSTO CON PANTALLA Pantalla no táctil de 4,3" resolución 480×272. Fuente de alimentación PoE estándar sin adaptador de corriente adicional. Visualiza vídeos en directo de estaciones de puerta y cámaras vinculadas. Conveniente para que los usuarios personalicen funciones según sus propios hábitos de uso mediante 4 botones táctiles personalizados', 'DISPONIBLE'),
  ('Hikvision', 'DS-KH6110-WE1', 'Hikvision DS-KH6110-WE1 ESTACIÓN INTERIOR IP DE BAJO COSTO CON PANTALLA Pantalla táctil de 4,3"', 'Domótica', 80.00, 'ESTACIÓN INTERIOR IP DE BAJO COSTO CON PANTALLA Pantalla táctil de 4,3" resolución 480×272. Fuente de alimentación PoE estándar sin adaptador de corriente adicional. Visualiza vídeos en directo de estaciones de puerta y cámaras vinculadas. Conveniente para que los usuarios personalicen funciones según sus propios hábitos de uso mediante 4 botones táctiles personalizados', 'DISPONIBLE'),
  ('Hikvision', 'DS-KH6220-LE1', 'Hikvision DS-KH6220-LE1 NO TOUCH) MONITOR PANTALLA 7" Pantalla NO TOUCH de 7" (botones', 'Domótica', 60.00, 'NO TOUCH) MONITOR PANTALLA 7" Pantalla NO TOUCH de 7" (botones físicos), 4 botones, Apertura remota y visualización en vivo, Resolución: 1024 x 600. Micrófono y Altavoz integrados, Ethernet TCP/IP, Micro SD 32G, PoE estándar, 8 Alarma IN, Fuente de Poder IEEE802.3af, standard PoE o 12 VDC/1 A', 'DISPONIBLE'),
  ('Hikvision', 'DS-KH6320-WTE1', 'Hikvision DS-KH6320-WTE1 MONITOR PANTALLA TACTIL 7" Micrófono y Altavoz integrados, Ethernet', 'Domótica', 110.00, 'MONITOR PANTALLA TACTIL 7" Micrófono y Altavoz integrados, Ethernet TCP/IP, Wi-Fi 802.11 b/g/n, Memoria 128MB, interfaz RS-485, Micro SD 32G, PoE estándar, 8 Alarma IN, 2 Salidas de Relé, Fuente de Poder IEEE802.3af, standard PoE O 12 VDC/1 A', 'DISPONIBLE'),
  ('Hikvision', 'DS-KH6350-WTE1/White', 'Hikvision DS-KH6350-WTE1/White Color Blanco MONITOR PANTALLA TACTIL 7" Nueva interfaz de usuario V2.0:', 'Domótica', 110.00, 'Color Blanco MONITOR PANTALLA TACTIL 7" Nueva interfaz de usuario V2.0: diseño fácil de usar. Pantalla táctil colorida de 7" resolución 1024 × 600. Micrófono y Altavoz integrados, Ethernet TCP/IP, Wi-Fi 802.11 b/g/n, Memoria 128MB, interfaz RS-485, Micro SD 32G, PoE estándar, 8 Alarma IN, 2 Salidas de Relé, Fuente de Poder IEEE802.3af, standard PoE O 12 VDC/1 A', 'DISPONIBLE'),
  ('Hikvision', 'DS-KH8350-WTE1', 'Hikvision DS-KH8350-WTE1 MONITOR PANTALLA TACTIL 7" Diseño ultra delgado (ganador de premiro', 'Domótica', 215.00, 'MONITOR PANTALLA TACTIL 7" Diseño ultra delgado (ganador de premiro Reddot award 2017), Cristal templado premium, Aluminio grado aeroespacial, Boton de apertura rápida, Micrófono bidireccional y Altavoz integrados, Ethernet TCP/IP, Wi-Fi 802.11 b/g/n, Memoria 128MB, interfaz RS-485, Micro SD 32G, PoE estándar, 8 Alarma IN, 2 Salidas de Relé, Fuente de Poder IEEE802.3af, standard PoE O 12 VDC/1 A - NO DISPONIBLE ESTATUS CONTROL DE ACCESO HIKVISION DS-KH9310-WTE1 MONITOR PANTALLA TACTIL 7" ESTACIÓ', 'DISPONIBLE'),
  ('Hikvision', 'DS-KM9503', 'Hikvision DS-KM9503 ESTACIÓN PRINCIPAL IP ANDROID TACTIL DE 10 PULGADAS Pantalla táctil IPS', 'Domótica', 629.00, 'ESTACIÓN PRINCIPAL IP ANDROID TACTIL DE 10 PULGADAS Pantalla táctil IPS de 10,1 pulgadas con resolución 1280×800 Servidor privado SIP incorporado, acceso a hasta 10.000 dispositivos de videoportero. Se pueden agregar hasta 128 cámaras de red Admite más de 2 parlantes y micrófonos: se conecta a un auricular externo (3,5 mm), micrófono externo de cuello de ganso Muestra páginas de operación a través de HDMI Admite fuente de alimentación PoE estándar y 12 VCC Funciones de videoportero y control de ', 'DISPONIBLE'),
  ('Hikvision', 'DS-KB8113-IME1(B)', 'Hikvision DS-KB8113-IME1(B) ESTACIÓN DE PUERTA IP - FRENTE DE CALLE ANTI-VANDALICO Cámara HD de 2', 'Domótica', 85.00, 'ESTACIÓN DE PUERTA IP - FRENTE DE CALLE ANTI-VANDALICO Cámara HD de 2 MP. Visión nocturna IR 3 metros. Nivel de protección: IP65/IK09 para exteriores. Comunicación bidireccional con supresión de eco. Micrófono y Altavoz integrados. Interfaz web y detección de movimiento. 1 Salida de Rele, 1 entrada de alarma, 1 interfaz de red TCP/IP. 1 botón', 'DISPONIBLE'),
  ('Hikvision', 'DS-KV6113-WPE1(C)', 'Hikvision DS-KV6113-WPE1(C) ESTACIÓN DE PUERTA VILLA METALICO (PUNTO DE CALLE) Cámara IP 2MP con IR', 'Domótica', 99.00, 'ESTACIÓN DE PUERTA VILLA METALICO (PUNTO DE CALLE) Cámara IP 2MP con IR Material Plastico Intemperie IP65 Antivandalico IK08 Lector de Tarjeta MIFARE (Control de Acceso) Alimentación: 12 VDC / PoE Estandar Intefaz Ethernet TCP/IP, RTSP / RS-485 4 x Entrada Alarma, 1 x Boton Salida, 1 x Cerradura, 1 x Contacto', 'DISPONIBLE'),
  ('Hikvision', 'DS-KV8113-WME1(C)', 'Hikvision DS-KV8113-WME1(C) ESTACIÓN DE PUERTA VILLA METALICO (PUNTO DE CALLE) Cámara IP 2MP con IR', 'Domótica', 120.00, 'ESTACIÓN DE PUERTA VILLA METALICO (PUNTO DE CALLE) Cámara IP 2MP con IR Metalico Intemperie IP65 Antivandalico IK08 Lector de Tarjeta MIFARE (Control de Acceso) Alimentación: 12 VDC / PoE Estandar Intefaz Ethernet TCP/IP, RTSP / RS-485 4 x Entrada Alarma, 2 x Boton Salida, 2 x Cerradura, 2 x Contacto', 'DISPONIBLE'),
  ('Hikvision', 'DS-KD9633-WBE6', 'Hikvision DS-KD9633-WBE6 ESTACIÓN PUERTA FACIAL MULTI APARTAMENTOS Operación intuitiva para una', 'Domótica', 775.00, 'ESTACIÓN PUERTA FACIAL MULTI APARTAMENTOS Operación intuitiva para una mejor experiencia de usuario. Pantalla LCD Táctil 10,1" 1280 × 880. Sistema Android incorporado. UI de pantalla táctil, WEB. Gran calidad de imagen incluso en la oscuridad. Cámara doble lente 2MP 3m IR. Múltiples autenticaciones inteligentes. Tarjeta, código PIN, bluetooth, código QR, huella digital y reconocimiento facial. Alto nivel de protección IK07. Intemperie IP65. 2 Microfonos Omnidireccionales. Interfaces: 2 RJ45 IP, ', 'DISPONIBLE'),
  ('Hikvision', 'DS-KDM9633-FKP', 'Hikvision DS-KDM9633-FKP MODULO DE HUELLA Y TECLADO PARA ESTACIÓN DS-KD9633 Capacidad de 5000', 'Domótica', 104.50, 'MODULO DE HUELLA Y TECLADO PARA ESTACIÓN DS-KD9633 Capacidad de 5000 huellas dactilares de alta Compensación de retroiluminación detrás del teclado Alto nivel de protección Intemperie IP65 y Antivandalismo IK07 Fácil de usar y ampliar, Conexión USB', 'DISPONIBLE'),
  ('Hikvision', 'DS-KD-KK', 'Hikvision DS-KD-KK MODULO DE BOTONES PARA VIDEOPORTERO MODULAR Etiquetas editables, 6', 'Domótica', 30.00, 'MODULO DE BOTONES PARA VIDEOPORTERO MODULAR Etiquetas editables, 6 Botones físicos para llamar a 6 monitores principales, Compatible con montaje empotrado o en superficie, Compensación de Luz de Fondo BLC, Configurable mediante IVMS4200, Intemperie IP65', 'DISPONIBLE'),
  ('Hikvision', 'DS-KD-KP', 'Hikvision DS-KD-KP MODULO DE TECLADO PARA VIDEOPORTERO MODULAR Apertura de puerta mediante', 'Domótica', 80.00, 'MODULO DE TECLADO PARA VIDEOPORTERO MODULAR Apertura de puerta mediante contraseña, llamada a monitor, Compatible con montaje empotrado o en superficie, Configurable mediante iVMS4200, Intemperie IP65', 'DISPONIBLE'),
  ('Hikvision', 'DS-KD-M', 'Hikvision DS-KD-M MODULO LECTOR TARJETA PARA VIDEOPORTERO MODULAR Lector de tarjeta', 'Domótica', 50.00, 'MODULO LECTOR TARJETA PARA VIDEOPORTERO MODULAR Lector de tarjeta Mifare, Frecuencia 13.56MHz, Soporta hasta 10,000 Tarjetas, Apertura de puerta mediante tarjeta, Compensación de Luz de Fondo BLC, Compatible con montaje empotrado o en superficie, Configurable mediante iVMS4200, Intemperie IP65', 'DISPONIBLE'),
  ('Hikvision', 'DS-KD-DIS', 'Hikvision DS-KD-DIS MODULO PANTALLA PARA VIDEOPORTERO MODULAR Apertura de puerta mediante', 'Domótica', 70.00, 'MODULO PANTALLA PARA VIDEOPORTERO MODULAR Apertura de puerta mediante contraseña, llamada a monitor, Compatible con montaje empotrado o en superficie, Configurable mediante iVMS4200, Intemperie IP65', 'DISPONIBLE'),
  ('Hikvision', 'DS-KD-TDM', 'Hikvision DS-KD-TDM MODULO PANTALLA TACTIL PARA VIDEOPORTERO MODULAR Soporta Control de', 'Domótica', 250.00, 'MODULO PANTALLA TACTIL PARA VIDEOPORTERO MODULAR Soporta Control de Acceso con Lector de tarjeta MIFARE, Pantalla de 4", Intemperie IP65, Antivandalismo IK8, Visualización de número de marcación, código PIN y desbloqueo con Tarjeta, Visualización de lista de contactos y Publicidad, Permite almacenar y buscar listas de contactos, Opción en Español, Salida de audio tipo Buzzer', 'DISPONIBLE'),
  ('Hikvision', 'DS-KD9203-ME6', 'Hikvision DS-KD9203-ME6 ESTACIÓN DE PUERTA METALICO (PUNTO DE CALLE) Cámara IP 2MP con IR', 'Domótica', 360.00, 'ESTACIÓN DE PUERTA METALICO (PUNTO DE CALLE) Cámara IP 2MP con IR, Angulo de Visión de 120 ° Pantalla LCD a color de 4.3" Control de Acceso mediante Rostro, Tarjeta M1 o código pin Soporta 5.000 Rostros / 50.000 Tarjetas / 10.000 Usuarios Intefaz Ethernet TCP/IP, RTSP / RS-485 Metalico Intemperie IP65 Alimentación: 12 VDC 4 x Entrada Alarma, 1 x Boton Salida, 1 x Cerradura, 2 x Contacto 315.00 DISPONIBLE ESTATUS CONTROL DE ACCESO HIKVISION DS-KD9203-MFE6 ESTACIÓN DE PUERTA METALICO (PUNTO DE CAL', 'DISPONIBLE'),
  ('Hikvision', 'DS-KD-ACF1/Plastic', 'Hikvision DS-KD-ACF1/Plastic EMPOTRAR) BASE 2 ESPACIOES PARA VIDEOPORTERO MODULAR Marco de', 'Domótica', 20.00, 'EMPOTRAR) BASE 2 ESPACIOES PARA VIDEOPORTERO MODULAR Marco de instalacion con caja para empotrar 1 módulos de frente de calle, Material plástico, Dimensiones: 237 x 134 × 56 mm.', 'DISPONIBLE'),
  ('Hikvision', 'DS-KD-ACF2/Plastic', 'Hikvision DS-KD-ACF2/Plastic EMPOTRAR) BASE 2 ESPACIOES PARA VIDEOPORTERO MODULAR Marco de', 'Domótica', 27.00, 'EMPOTRAR) BASE 2 ESPACIOES PARA VIDEOPORTERO MODULAR Marco de instalacion con caja para empotrar 2 módulos de frente de calle, Material plástico, Dimensiones: 237 x 134 × 56 mm.', 'DISPONIBLE'),
  ('Hikvision', 'DS-KD-ACF3/Plastic', 'Hikvision DS-KD-ACF3/Plastic EMPOTRAR) BASE 3 ESPACIOES PARA VIDEOPORTERO MODULAR Marco de', 'Domótica', 35.00, 'EMPOTRAR) BASE 3 ESPACIOES PARA VIDEOPORTERO MODULAR Marco de instalacion con caja para empotrar 3 módulos de frente de calle, Material plástico, Dimensiones: 338.8 x 134 × 56 mm.', 'DISPONIBLE'),
  ('Hikvision', 'DS-QAZ1120G1-B/EU', 'Hikvision DS-QAZ1120G1-B/EU ALTAVOZ DE GABINETE DE RED DE 20W Chips de doble núcleo de grado', 'Domótica', 70.00, 'ALTAVOZ DE GABINETE DE RED DE 20W Chips de doble núcleo de grado industrial de alta velocidad, almacenamiento dual NOR Flash+EMMC incorporado, admita copia de seguridad dual del sistema para garantizar un rendimiento estable Inicio seguro, mecanismo de bloqueo de inicio de sesión de usuario y solicitudes de complejidad de contraseña, admite trazabilidad de registros de auditoría de seguridad y mejora la seguridad de la red Gestión unificada por lotes de plataformas remotas a través de redes IP (', 'DISPONIBLE'),
  ('Hikvision', 'DS-QAE1A80G1-VB', 'Hikvision DS-QAE1A80G1-VB AMPLIFICADOR IP DE 2 ZONAS DE 80W Tareas en tiempo real y programadas', 'Domótica', 195.00, 'AMPLIFICADOR IP DE 2 ZONAS DE 80W Tareas en tiempo real y programadas, reanudación de reproducción y gestión de bibliotecas de audio. Entrada y salida de alarma, programación de armado y enlace de audio. Admite síntesis de voz TTS y transmisión de texto, con opciones de audio dual macho y hembra estándar, fluidas y naturales. Admite múltiples tipos de entrada de audio: Bluetooth, memoria USB 2.0/3.0, micrófono y RCA, con un funcionamiento flexible y práctico. Control de volumen independiente par', 'DISPONIBLE'),
  ('Hikvision', 'DS-QAE0206G1-V', 'Hikvision DS-QAE0206G1-V ALTAVOZ DE TECHO ANALOGICO DE 6W Altavoz Montaje en Plafón. 6 Watts', 'Domótica', 15.00, 'ALTAVOZ DE TECHO ANALOGICO DE 6W Altavoz Montaje en Plafón. 6 Watts. 100 V. Rejilla de Metal. Color Blanco. Uso Interior. Entrada de audio 100V, potencia de salida de 60W Nivel máximo de sonido hasta 96dB. Instalación rápida, abrazadera de resorte de acero. Conectividad Bluetooth para transmisión inalámbrica. Reproductor MP3 integrado, control de micrófono independiente. Altavoz compatible con amplificador DS-QAE0A60G1-VB ideal para musica ambiental y mensajes de voz. Dimensiones: Ø 170 mm × 64 ', 'DISPONIBLE'),
  ('Hikvision', 'DS-QAE0420G1-V', 'Hikvision DS-QAE0420G1-V ALTAVOZ DE COLUMNA ANALOGICO Revestimiento adhesivo importado magnético', 'Domótica', 75.00, 'ALTAVOZ DE COLUMNA ANALOGICO Revestimiento adhesivo importado magnético aeroespacial, diseño de película sonora liviana, con alta Plásticos reforzados de ingeniería profesional con alta resistencia. Entrada de audio: extremo verde (bloque de terminales), entrada de voltaje constante: 100 V, COM. Protección de aprobación: IP66 Al usar soportes en L, el ángulo de la superficie de instalación se puede ajustar para una instalación conveniente Diseño integrado profesional, resistente al agua IP66, co', 'DISPONIBLE'),
  ('Hikvision', 'DS-QAE0206G1E-V', 'Hikvision DS-QAE0206G1E-V ALTAVOZ DE TECHO ANALOGICO Al adoptar un lavabo acústico de fibra de', 'Domótica', 170.00, 'ALTAVOZ DE TECHO ANALOGICO Al adoptar un lavabo acústico de fibra de papel compuesto, la calidad del sonido es clara y brillante. Con el diseño de una poderosa abrazadera de resorte de acero, la instalación es rápida y segura Soporte de instalación de montaje en techo con una apariencia simple Potencia nominal: 6 W. Sensibilidad: 91 dB ±3dB. Máx. Presión acústica: 98 dB. Respuesta de frecuencia: 90 Hz a 20 kHz Entrada de audio: voltaje nominal, 100 V Dimensiones: Ø170 ×64 mm(Ø6.69" × 2.52") / Pe', 'DISPONIBLE'),
  ('Hikvision', 'DS-TDSB00-EKT', 'Hikvision DS-TDSB00-EKT RADAR DE DETECCIÓN DE CAIDAS Sin divulgación de privacidad. Detección', 'Domótica', 190.00, 'RADAR DE DETECCIÓN DE CAIDAS Sin divulgación de privacidad. Detección de postura sin contacto. Alta precisión de detección y baja tasa de falsas alarmas. Detecta personas y no personas en la zona. Admite localizar el objetivo y transmitir la ubicación. Admite un rango de detección de 4 m x 5 m. Admite la transmisión de datos a la plataforma mediante protocolo OTAP. Admite conexión a Wi-Fi y red cableada IP RJ45. Admite la detección del cuerpo humano, la detección de caídas y el rastreo de objeti', 'DISPONIBLE'),
  ('Hikfire', 'HF-S2', 'Hikfire HF-S2 DETECTOR DE HUMO AUTONOMO (STAND-ALONE) Detector de Humo Óptico', 'Domótica', 15.00, 'DETECTOR DE HUMO AUTONOMO (STAND-ALONE) Detector de Humo Óptico Hikvision. Tecnología Avanzada de Detección de Incendios. Alarma Temprana y Fiabilidad Certificada. Soporta Salida de Alarma. Detector de humo (E/S). Interfaz de E/S compatible. 3 años de batería. ideal para detectar humo y fuego, y emite señales de alarma sonoras y visuales, siendo ampliamente utilizado en tiendas, residencias, hoteles y otros escenarios independientes. El detector es autónomo, no requiere un panel. Incorpora funci', 'DISPONIBLE'),
  ('Hikfire', 'HF-GN110', 'Hikfire HF-GN110 DETECTOR DE GAS NATURAL METANO CH4 (STAND-ALONE) Alarma Temprana', 'Domótica', 34.00, 'DETECTOR DE GAS NATURAL METANO CH4 (STAND-ALONE) Alarma Temprana. Salida para cierre de Válvula y/o activación de Ventilador. Protección IP30. Alarma de 70dB a 115dB a 1 metro de distancia. Alerta temprana para fuga de gas natural. Rango de medición hasta 25% LEL. Volumen de alarma de 70db a 115db. Salidas para válvula y ventilador. Certificación: GB 15322.2-2019.', 'DISPONIBLE'),
  ('Hikfire', 'HF-GP110', 'Hikfire HF-GP110 DETECTOR DE GAS LP PROPANO C3H8 (STAND-ALONE) Alarma Temprana. Salida', 'Domótica', 36.50, 'DETECTOR DE GAS LP PROPANO C3H8 (STAND-ALONE) Alarma Temprana. Salida para cierre de Válvula y/o activación de Ventilador. Protección IP30. Alarma de 70dB a 115dB a 1 metro de distancia. Detección de gas C3H8 con alerta temprana. Alarma sonora 70dB~115dB a 1m. Rango de medición 0~25% LEL. Umbral de alarma al 10% LEL. Fuente de alimentación AC 220V', 'DISPONIBLE'),
  ('Hikfire', 'HF-CAB1', 'Hikfire HF-CAB1 TIMBRE DE ALARMA CONVENCIONAL Con una cubierta de aleación de aluminio', 'Domótica', 15.00, 'TIMBRE DE ALARMA CONVENCIONAL Con una cubierta de aleación de aluminio, es ligero, ofrece un alto volumen de sonido y es fácil de instalar. Bajo consumo, alta fiabilidad. Norma ejecutiva: GB 26851-2011 Nivel de presión sonora (dB SPL): 75 dB ~ 100 dB Entorno de funcionamiento: Interior Dimensiones del producto: φ 150 mm × H 55 mm Tipo de instalación: Montaje en pared', 'DISPONIBLE'),
  ('Hikvision', 'DS-PHA20-W2P', 'Hikvision DS-PHA20-W2P Acceso a 2 camaras ip estandar 802.11b/g/n central de alarma hibrida de', 'Domótica', 75.00, 'Acceso a 2 camaras ip estandar 802.11b/g/n central de alarma hibrida de 20 zonas (caja plastica) 4 particiones, 4 zonas en tarjeta, expandible a 16 zonas cableadas / inalambricas, 2 saildas en tarjeta, expandible a 18 salidas cableadas / inalambricas, interface: 1 ethernet rj45 10m/100m, comunicación lan, pstn, gprs y 3g/4g (con modulo), caja plastica, bateria litium, 1 sirena cableada, 2 sirenas inalambricas', 'DISPONIBLE'),
  ('Hikvision', 'DS-PHA32-P/LA', 'Hikvision DS-PHA32-P/LA Central de alarma hibrida de 32 zonas (caja plastica) 32 entradas', 'Domótica', 79.00, 'Central de alarma hibrida de 32 zonas (caja plastica) 32 entradas inalámbricas, 4 expansores de salida inalámbrica. múltiples métodos de comunicación: lan + wi-fi. 2 canales. verificación por video a bordo. compatible con el protocolo sia-contact id. zonas: 32. particiones: 16. usuarios: 30 operarios 1 instalador 1 admin. notificaciones: sms/gprs/3g/4g. herramienta programación: teclado web(ivms-4200/hik-proconnet', 'DISPONIBLE'),
  ('Hikvision', 'DS-PHA48-EP', 'Hikvision DS-PHA48-EP Central de alarma hibrida 48 zonas (caja plastica) 8 zonas en tarjeta', 'Domótica', 89.00, 'Central de alarma hibrida 48 zonas (caja plastica) 8 zonas en tarjeta, expandible a 48 zonas cableadas o inalambricas, 4 saildas en tarjeta, 1 salida para sirena cableada / expandible a 44 salidas cableadas / inalambricas, comunicación lan, pstn, gprs, 3g/4g, 2 canales para camaras ip, protocolos isapi, cloud p2p, isup, csv-ip, dc-09 / 2 switchs anti vandalismo', 'DISPONIBLE'),
  ('Hikvision', 'DS-PHA64-LP', 'Hikvision DS-PHA64-LP Central de alarma hibrida 64zonas (caja plastica) 8 zonas en tarjeta', 'Domótica', 99.00, 'Central de alarma hibrida 64zonas (caja plastica) 8 zonas en tarjeta, expandible a 64 zonas cableadas o inalambricas, 4 saildas en tarjeta, 1 salida para sirena cableada. expandible a 44 salidas cableadas. inalambricas, comunicación lan, wi-fi, pstn, gprs, 3g/4g, 2 canales para camaras ip, protocolos isapi, cloud p2p, isup, csv-ip, dc-09 / 2 switchs anti vandalismo', 'DISPONIBLE'),
  ('Hikvision', 'DS-PHA64-Kit-WB', 'Hikvision DS-PHA64-Kit-WB Kit alarma ax pro hibrido 64 zonas contiene:- 1 central de alarma', 'Domótica', 124.00, 'Kit alarma ax pro hibrido 64 zonas contiene:- 1 central de alarma ds-pha64-lp / 2 sensores de movimiento pir ds-pdp18-eg2 / 1 teclado lcd ds-pk1- lrt-hwb / 1 control remoto ds-pkf1-wb / 1 contacto magnético ds-pd1-mc-ws comunicación lan, wi-fi, pstn, gprs, 3g/4g, 2 canales para camaras ip, protocolos isapi, cloud p2p, isup, csv-ip, dc-09 / 2 switchs anti vandalismo - no disponible sistemas de alarmas estatus control de acceso hikvision ds-pha64-w4m acceso a 4 camaras ip estandar 802.11b/g/n cent', 'DISPONIBLE'),
  ('Hikvision', 'DS-PHA64-W4P2', 'Hikvision DS-PHA64-W4P2 Central de alarma hibrida caja metálica 8 particiones, 8 zonas en', 'Domótica', 99.00, 'Central de alarma hibrida caja metálica 8 particiones, 8 zonas en tarjeta, expandible a 64 zonas cableadas / inalambricas, 4 saildas en tarjeta, expandible a 60 salidas cableadas / inalambricas, interface ip rj45, comunicación lan, pstn, gprs y 3g/4g (con modulo), caja metalica permite incluir bateria, 1 sirena cableada, 2 sirenas inalambricas', 'DISPONIBLE'),
  ('Hikvision', 'DS-PA-Battery', 'Hikvision DS-PA-Battery Batería de respaldo para panel de alarma hikvision 4520 mah. compatible', 'Domótica', 24.00, 'Batería de respaldo para panel de alarma hikvision 4520 mah. compatible con paneles ax pro - ax hub - hibrido versión 1 (ds-pha64-w4p) y repetidor ax pro ds- pr1-wb. peso ligero de solo 80 gramos. dimensiones compactas: 59 x 69 x 8 mm. compatibilidad con series verificables en línea. optimizada para paneles de alarma hikvision', 'DISPONIBLE'),
  ('Hikvision', 'DS-PKG-H8L', 'Hikvision DS-PKG-H8L 8 zonas', 'Domótica', 30.00, '8 zonas', 'DISPONIBLE'),
  ('Hikvision', 'DS-PK-L', 'Hikvision DS-PK-L Blanco) teclado cableado lcd (color blanco) pantalla lcd 80 x 25 mm', 'Domótica', 29.00, 'Blanco) teclado cableado lcd (color blanco) pantalla lcd 80 x 25 mm. pantalla de 2 lineas muestra nombre de zona, estados y eventos en tiempo real en pantalla lcd', 'DISPONIBLE');

update public.products p
set
  nombre = e.nombre,
  categoria = e.categoria,
  marca = e.marca,
  descripcion = e.descripcion,
  descripcion2 = 'Lista distribuidor 2026 · ' || e.estatus,
  costo = e.costo,
  precio = e.costo,
  utilidad = 0
from cat_acceso_2026 e
where lower(btrim(p.modelo)) = lower(btrim(e.modelo))
  and (
    p.marca is null
    or btrim(p.marca) = ''
    or lower(btrim(p.marca)) = lower(btrim(e.marca))
  );

insert into public.products (
  nombre, categoria, marca, modelo, descripcion, descripcion2,
  costo, precio, utilidad, cantidad
)
select
  e.nombre, e.categoria, e.marca, e.modelo, e.descripcion,
  'Lista distribuidor 2026 · ' || e.estatus,
  e.costo, e.costo, 0, 0
from cat_acceso_2026 e
where not exists (
  select 1
  from public.products p
  where lower(btrim(p.modelo)) = lower(btrim(e.modelo))
    and (
      p.marca is null
      or btrim(p.marca) = ''
      or lower(btrim(p.marca)) = lower(btrim(e.marca))
    )
);

commit;

select marca, count(*) as n
from public.products
where lower(btrim(coalesce(marca, ''))) in ('hikvision', 'hikfire', 'ubiquiti', 'omegasat')
group by 1
order by 1;

