import { parseCantidadDesdeDescripcion } from '../lib/contabilidad/cco/parseCantidadDesdeDescripcion';

const descs = [
  '3 PALETAS DE CEMENTO (100%)',
  'MADERAS EL BOSQUE MODULO B (48%)',
  'COMPRA 120 PARES DE GUANTES (48%)',
  'COMPRA DE 6 ROLLOS DE ALAMBRE MAS 600GR FIBRA/CONCR (48%)',
  'COMPRA DE CABILLAS 15 DE 1/2 + 30 DE 3/8 (48%)',
  '8 GALONES DE INHIBIDOR DE OXIDO (48%)',
  'ABRAZADERA, LLAVE DE MANGUERA, CODO, TEFLON, NIPLE',
  'CEMENTO PLASTICO, UN CUÑETE, CEPILLO, MANGUERA (48%)',
  'BURBUJAS PLASTIC FACT 25544 (PLASTICO PARA GUARDAR ARTICULOS DE VIDRIO) (48%)',
  'MATERIAL ELECTRICO,TUBERIAS, CAJETINES, COTIZACION 04215 (48%)',
  'TUBERIAS DE AGUAS NEGRAS Y AGUAS BLANCAS, CONEXIONES, ETC, VER COTIZACION 04213 (48%)',
  'FORMULA MARINA MAS CLAVOS, CANDADOS (48%)',
  '20 ROLLOS DE MANTO, 2 ROLLOS DE MALLA TRUCSON (48%)',
  '19 HORCONOES,  CAÑA BRAVA (MADERA PARA ESTRUCURA DE MODULO A) (48%)',
  '10 ROLLOS DE ALAMBRE, VER FACTURA (48%)',
  'COMPRA DE 6 PALETAS DE CEMENTO A GRANEL (48%)',
  'COMPRA DE LAMINA DE PLAYCEN  (ENCOFRADO CANAL DEL BUNKER-MODULO E) (48%)'
];

for (const d of descs) {
  console.log(d, '=>', parseCantidadDesdeDescripcion(d));
}
