-- 336 · Contrato individual por obra determinada: Cl. SEXTA y SÉPTIMA
-- SEXTA: salario diario del oficio + cesta ticket + complemento de alimentación (33 USD).
-- SÉPTIMA: 90 USD ayudante / 115 USD clasificado; nace cada 4 semanas y se paga al finiquito.

update public.ci_legal_plantillas
set cuerpo_markdown = $cuerpo$CONTRATO INDIVIDUAL DE TRABAJO POR OBRA DETERMINADA

Entre {{PATRON_RAZON_SOCIAL}}, Sociedad Mercantil domiciliada en {{PATRON_DOMICILIO}}, Municipio {{PATRON_MUNICIPIO}} del estado {{PATRON_ESTADO}}, {{PATRON_INSCRIPCION_RM}} representada en este acto por su {{REP_LEGAL_CARGO}} {{REP_LEGAL_ARTICULO_CIUDADANO}} {{REP_LEGAL_NOMBRE}}, {{REP_LEGAL_NACIONALIDAD}}, mayor de edad, hábil en derecho, {{REP_LEGAL_ESTADO_CIVIL}}, de este domicilio, titular de la cédula de identidad N° {{REP_LEGAL_CEDULA}}, quien a los efectos de este contrato se denominará LA ENTIDAD DE TRABAJO, por una parte; y por la otra, {{EMPLEADO_ARTICULO_CIUDADANO}} {{EMPLEADO_NOMBRE_COMPLETO}}, {{EMPLEADO_NACIONALIDAD}}, mayor de edad, hábil en derecho, {{EMPLEADO_ESTADO_CIVIL}}, de este domicilio, titular de la cédula de identidad N° {{EMPLEADO_CEDULA}}, quien en lo sucesivo se denominará EL TRABAJADOR, se ha convenido en celebrar el presente Contrato de Trabajo para una Obra Determinada, conforme al artículo 63 de la LOTTT y a las Cláusulas 18 y 19 de la Convención Colectiva de Trabajo para la Rama de la Industria de la Construcción, el cual se regirá por las cláusulas siguientes:

PRIMERA: OBJETO Y MODALIDAD. Este contrato se celebra bajo la modalidad de OBRA DETERMINADA (artículo 63 de la LOTTT y Cláusulas 18 y 19 de la Convención Colectiva), para la ejecución de la fase técnica de: {{CONTRATO_FASE_TECNICA}}, dentro de la obra denominada: {{OBRA_NOMBRE}}. LA ENTIDAD DE TRABAJO contrata a EL TRABAJADOR para desempeñar el cargo de {{CONTRATO_CARGO_OFICIO}}, establecido en el Tabulador de Oficios y Salarios Básicos de la Convención Colectiva. EL TRABAJADOR se obliga a: 1. Poner a disposición su capacidad normal de trabajo durante la jornada, en las labores convenidas y en las anexas o complementarias. 2. Ejecutar las actividades inherentes al cargo. 3. Usar obligatoriamente el uniforme y los equipos de protección (guantes, lentes, botas, etc.) según la LOPCYMAT. 4. Mantener el orden del área asignada y el buen estado de maquinarias y herramientas. 5. No realizar, por cuenta propia o ajena, actividades que compitan con las de LA ENTIDAD DE TRABAJO, ni utilizar en ellas sus equipos, materiales o información.

SEGUNDA: PERÍODO DE PRUEBA. Conforme a la Cláusula 10 de la Convención Colectiva, se acuerda un PERÍODO DE PRUEBA DE TREINTA (30) DÍAS. Durante este lapso, LA ENTIDAD DE TRABAJO apreciará los conocimientos y aptitudes de EL TRABAJADOR. Cualquiera de las partes podrá dar por terminada la relación sin indemnización por despido, y LA ENTIDAD DE TRABAJO pagará los salarios y demás conceptos causados hasta esa fecha.

TERCERA: DURACIÓN Y TERMINACIÓN. La relación de trabajo está sujeta a la culminación física de la fase técnica descrita en la Cláusula Primera. El vínculo terminará con la conclusión de dicha fase, conforme al artículo 63 de la LOTTT y a la Cláusula 19 de la Convención Colectiva, lo que se hará constar en el Acta de Culminación asentada en el Libro de Obra por el Supervisor. La terminación es independiente de la entrega formal del inmueble al propietario. En esa oportunidad, LA ENTIDAD DE TRABAJO pagará a EL TRABAJADOR las prestaciones sociales y demás conceptos que le correspondan, conforme al artículo 142 de la LOTTT y a la Cláusula 51 de la Convención Colectiva.

CUARTA: JORNADA, HORARIO Y RENDIMIENTO. Conforme al artículo 173 de la LOTTT y a la Cláusula 6 de la Convención Colectiva, la jornada semanal será de cuarenta (40) horas de trabajo efectivo: {{CONTRATO_HORARIO_CUARTA}} CONTROL: EL TRABAJADOR debe firmar diariamente su registro de avance en el Libro de Obra. La inobservancia del horario en cuatro (4) oportunidades en un mes, o la negativa a firmar el registro, podrá constituir falta grave a las obligaciones que impone la relación de trabajo, conforme al artículo 79, literal "i", de la LOTTT.

QUINTA: LUGAR DE TRABAJO Y DIRECCIÓN. Los servicios se prestarán en: {{CONTRATO_LUGAR_QUINTA}}. LA ENTIDAD DE TRABAJO ejercerá su facultad de dirección para el mejor desempeño de la obra; dichas exigencias técnicas y de rendimiento no se considerarán acoso laboral.

SEXTA: SALARIO Y BENEFICIOS SOCIALES. EL TRABAJADOR devengará los siguientes conceptos pagaderos en Bolívares:
a.- Bs. {{CONTRATO_SALARIO_DIARIO_VES}} diarios por el oficio de {{CONTRATO_OFICIO_TABULADOR}} según el Tabulador de Oficios y Salarios Básicos de la Convención Colectiva, con el aumento del cien por ciento (100%), es decir, dos (2) veces dicho salario, equivalente a Bs. {{CONTRATO_SALARIO_SEMANAL_VES}} semanales, conforme al acuerdo de la Comisión de Avenimiento de fecha 17 de agosto de 2026, homologado por auto N° 2026-021 de fecha 19 de agosto de 2026;
b.- Cesta Ticket: el equivalente en Bolívares de {{CONTRATO_CESTA_TICKET_USD_SEMANAL}} semanales, a la tasa oficial del BCV del día del pago; y
c.- COMPLEMENTO DEL BENEFICIO DE ALIMENTACIÓN (beneficio social de carácter no remunerativo): De conformidad con el numeral 2 del artículo 105 de la LOTTT, LA ENTIDAD DE TRABAJO otorgará a EL TRABAJADOR un complemento del Cesta Ticket por la cantidad fija de {{CONTRATO_COMPLEMENTO_ALIMENTACION_USD}} semanales, con la finalidad de coadyuvar a que él y su grupo familiar obtengan una alimentación adecuada frente a la pérdida del poder adquisitivo. Este complemento no es contraprestación del servicio; no depende del oficio, de la productividad ni de la asistencia; no forma parte del salario y no se computará para el cálculo de prestaciones sociales, vacaciones, bono vacacional, utilidades ni ningún otro concepto derivado de la relación de trabajo. Es un beneficio voluntario de LA ENTIDAD DE TRABAJO, que podrá suspenderlo o modificarlo con carácter general para todos sus trabajadores, sin que su pago en semanas anteriores genere derecho adquirido. Cuando el salario o el Cesta Ticket se modifiquen por decreto del Ejecutivo Nacional, por la Convención Colectiva o por actas homologadas, LA ENTIDAD DE TRABAJO podrá revisar, con carácter general, el monto de este complemento. Se pagará en partida separada, identificada en cada recibo como "Complemento del beneficio de alimentación". Todos los pagos se realizarán en Bolívares calculados a la tasa oficial del Banco Central de Venezuela (BCV) del día del pago.

SÉPTIMA: SEMANA ADICIONAL POR MES (PRESTACIONES, VACACIONES Y UTILIDADES). Cada cuatro (4) semanas trabajadas se genera a favor de EL TRABAJADOR el derecho a una (1) semana adicional, de monto fijo equivalente a {{CONTRATO_SEMANA_ADICIONAL_USD}} según el oficio (90,00 USD para ayudante y 115,00 USD para clasificado), pagadero en Bolívares a la tasa oficial del BCV del día del pago. Ese derecho se destina al pago de las prestaciones sociales, las vacaciones, el bono vacacional, las utilidades y demás conceptos que le correspondan conforme a la LOTTT y a la Convención Colectiva. Al sacar la cuenta, este beneficio es mayor que el que resultaría de pagar únicamente las alícuotas legales y convencionales de esos conceptos calculadas sobre el salario del Tabulador. El pago de las semanas adicionales causadas se efectuará al terminar la relación de trabajo (cierre de obra o finiquito), y no durante su vigencia. Al finiquito se pagará también la fracción que corresponda a las semanas trabajadas que no completen un ciclo de cuatro (4). En esa oportunidad el pago se imputa en este orden: a) a la garantía de prestaciones sociales, conforme al artículo 142 de la LOTTT y a la Cláusula 50 de la Convención Colectiva; b) a las utilidades de la Cláusula 48; c) a las vacaciones y al bono vacacional de la Cláusula 47; y d) el remanente, como complemento voluntario del beneficio de alimentación, sin carácter salarial. Cada recibo discriminará los conceptos.

OCTAVA: ÉTICA Y CONFIDENCIALIDAD. EL TRABAJADOR guardará reserva absoluta sobre la información técnica de la obra y se abstendrá de prácticas desleales.

NOVENA: TRANSPORTE GRATUITO (BENEFICIO SOCIAL NO REMUNERATIVO). LA ENTIDAD DE TRABAJO brindará de manera gratuita un servicio de transporte diario, de ida y vuelta, desde el punto de encuentro establecido {{OBRA_PUNTO_ENC_TRANSPORTE}} hasta el sitio de la obra. NATURALEZA JURÍDICA: conforme al artículo 105 de la LOTTT, este servicio es un beneficio social de carácter no remunerativo: no forma parte del salario, no es salario en especie y no se computará para prestaciones sociales, vacaciones, utilidades, bonos ni ningún otro concepto laboral. CONDICIONES: su uso es opcional para EL TRABAJADOR y está sujeto a las normas de conducta y seguridad dictadas por la empresa durante el trayecto.

DÉCIMA: DOMICILIO PROCESAL. Las partes eligen como domicilio especial la ciudad de {{CONTRATO_DOMICILIO_PROCESAL}}, Estado Nueva Esparta, sin perjuicio de la competencia que la Ley Orgánica Procesal del Trabajo atribuye a los Tribunales del Trabajo. Se firman dos (2) ejemplares de un mismo tenor y a un solo efecto, en {{CONTRATO_DOMICILIO_PROCESAL}}, a los {{CONTRATO_DIA_FIRMA}} días del mes de {{CONTRATO_MES_FIRMA}} del año {{CONTRATO_ANIO_FIRMA}}.

POR LA ENTIDAD DE TRABAJO                          POR EL TRABAJADOR

_______________________________                    _______________________________
{{REP_LEGAL_NOMBRE}}                               {{EMPLEADO_NOMBRE_COMPLETO}}
C.I. {{REP_LEGAL_CEDULA}}                          C.I. {{EMPLEADO_CEDULA}}
{{REP_LEGAL_CARGO}}                                (Huella dactilar)$cuerpo$,
    descripcion = 'Contrato individual de trabajo por obra determinada (CCT Construcción; Cl. SEXTA salario del oficio y Cl. SÉPTIMA semana adicional de 90/115 USD al finiquito).',
    updated_at = now()
where codigo in ('contrato_individual_obra_determinada_ve', 'contrato_laboral_obra_ve');

update public.ci_documento_plantillas
set cuerpo = $cuerpo$CONTRATO INDIVIDUAL DE TRABAJO POR OBRA DETERMINADA

Entre {{PATRON_RAZON_SOCIAL}}, Sociedad Mercantil domiciliada en {{PATRON_DOMICILIO}}, Municipio {{PATRON_MUNICIPIO}} del estado {{PATRON_ESTADO}}, {{PATRON_INSCRIPCION_RM}} representada en este acto por su {{REP_LEGAL_CARGO}} {{REP_LEGAL_ARTICULO_CIUDADANO}} {{REP_LEGAL_NOMBRE}}, {{REP_LEGAL_NACIONALIDAD}}, mayor de edad, hábil en derecho, {{REP_LEGAL_ESTADO_CIVIL}}, de este domicilio, titular de la cédula de identidad N° {{REP_LEGAL_CEDULA}}, quien a los efectos de este contrato se denominará LA ENTIDAD DE TRABAJO, por una parte; y por la otra, {{EMPLEADO_ARTICULO_CIUDADANO}} {{EMPLEADO_NOMBRE_COMPLETO}}, {{EMPLEADO_NACIONALIDAD}}, mayor de edad, hábil en derecho, {{EMPLEADO_ESTADO_CIVIL}}, de este domicilio, titular de la cédula de identidad N° {{EMPLEADO_CEDULA}}, quien en lo sucesivo se denominará EL TRABAJADOR, se ha convenido en celebrar el presente Contrato de Trabajo para una Obra Determinada, conforme al artículo 63 de la LOTTT y a las Cláusulas 18 y 19 de la Convención Colectiva de Trabajo para la Rama de la Industria de la Construcción, el cual se regirá por las cláusulas siguientes:

PRIMERA: OBJETO Y MODALIDAD. Este contrato se celebra bajo la modalidad de OBRA DETERMINADA (artículo 63 de la LOTTT y Cláusulas 18 y 19 de la Convención Colectiva), para la ejecución de la fase técnica de: {{CONTRATO_FASE_TECNICA}}, dentro de la obra denominada: {{OBRA_NOMBRE}}. LA ENTIDAD DE TRABAJO contrata a EL TRABAJADOR para desempeñar el cargo de {{CONTRATO_CARGO_OFICIO}}, establecido en el Tabulador de Oficios y Salarios Básicos de la Convención Colectiva. EL TRABAJADOR se obliga a: 1. Poner a disposición su capacidad normal de trabajo durante la jornada, en las labores convenidas y en las anexas o complementarias. 2. Ejecutar las actividades inherentes al cargo. 3. Usar obligatoriamente el uniforme y los equipos de protección (guantes, lentes, botas, etc.) según la LOPCYMAT. 4. Mantener el orden del área asignada y el buen estado de maquinarias y herramientas. 5. No realizar, por cuenta propia o ajena, actividades que compitan con las de LA ENTIDAD DE TRABAJO, ni utilizar en ellas sus equipos, materiales o información.

SEGUNDA: PERÍODO DE PRUEBA. Conforme a la Cláusula 10 de la Convención Colectiva, se acuerda un PERÍODO DE PRUEBA DE TREINTA (30) DÍAS. Durante este lapso, LA ENTIDAD DE TRABAJO apreciará los conocimientos y aptitudes de EL TRABAJADOR. Cualquiera de las partes podrá dar por terminada la relación sin indemnización por despido, y LA ENTIDAD DE TRABAJO pagará los salarios y demás conceptos causados hasta esa fecha.

TERCERA: DURACIÓN Y TERMINACIÓN. La relación de trabajo está sujeta a la culminación física de la fase técnica descrita en la Cláusula Primera. El vínculo terminará con la conclusión de dicha fase, conforme al artículo 63 de la LOTTT y a la Cláusula 19 de la Convención Colectiva, lo que se hará constar en el Acta de Culminación asentada en el Libro de Obra por el Supervisor. La terminación es independiente de la entrega formal del inmueble al propietario. En esa oportunidad, LA ENTIDAD DE TRABAJO pagará a EL TRABAJADOR las prestaciones sociales y demás conceptos que le correspondan, conforme al artículo 142 de la LOTTT y a la Cláusula 51 de la Convención Colectiva.

CUARTA: JORNADA, HORARIO Y RENDIMIENTO. Conforme al artículo 173 de la LOTTT y a la Cláusula 6 de la Convención Colectiva, la jornada semanal será de cuarenta (40) horas de trabajo efectivo: {{CONTRATO_HORARIO_CUARTA}} CONTROL: EL TRABAJADOR debe firmar diariamente su registro de avance en el Libro de Obra. La inobservancia del horario en cuatro (4) oportunidades en un mes, o la negativa a firmar el registro, podrá constituir falta grave a las obligaciones que impone la relación de trabajo, conforme al artículo 79, literal "i", de la LOTTT.

QUINTA: LUGAR DE TRABAJO Y DIRECCIÓN. Los servicios se prestarán en: {{CONTRATO_LUGAR_QUINTA}}. LA ENTIDAD DE TRABAJO ejercerá su facultad de dirección para el mejor desempeño de la obra; dichas exigencias técnicas y de rendimiento no se considerarán acoso laboral.

SEXTA: SALARIO Y BENEFICIOS SOCIALES. EL TRABAJADOR devengará los siguientes conceptos pagaderos en Bolívares:
a.- Bs. {{CONTRATO_SALARIO_DIARIO_VES}} diarios por el oficio de {{CONTRATO_OFICIO_TABULADOR}} según el Tabulador de Oficios y Salarios Básicos de la Convención Colectiva, con el aumento del cien por ciento (100%), es decir, dos (2) veces dicho salario, equivalente a Bs. {{CONTRATO_SALARIO_SEMANAL_VES}} semanales, conforme al acuerdo de la Comisión de Avenimiento de fecha 17 de agosto de 2026, homologado por auto N° 2026-021 de fecha 19 de agosto de 2026;
b.- Cesta Ticket: el equivalente en Bolívares de {{CONTRATO_CESTA_TICKET_USD_SEMANAL}} semanales, a la tasa oficial del BCV del día del pago; y
c.- COMPLEMENTO DEL BENEFICIO DE ALIMENTACIÓN (beneficio social de carácter no remunerativo): De conformidad con el numeral 2 del artículo 105 de la LOTTT, LA ENTIDAD DE TRABAJO otorgará a EL TRABAJADOR un complemento del Cesta Ticket por la cantidad fija de {{CONTRATO_COMPLEMENTO_ALIMENTACION_USD}} semanales, con la finalidad de coadyuvar a que él y su grupo familiar obtengan una alimentación adecuada frente a la pérdida del poder adquisitivo. Este complemento no es contraprestación del servicio; no depende del oficio, de la productividad ni de la asistencia; no forma parte del salario y no se computará para el cálculo de prestaciones sociales, vacaciones, bono vacacional, utilidades ni ningún otro concepto derivado de la relación de trabajo. Es un beneficio voluntario de LA ENTIDAD DE TRABAJO, que podrá suspenderlo o modificarlo con carácter general para todos sus trabajadores, sin que su pago en semanas anteriores genere derecho adquirido. Cuando el salario o el Cesta Ticket se modifiquen por decreto del Ejecutivo Nacional, por la Convención Colectiva o por actas homologadas, LA ENTIDAD DE TRABAJO podrá revisar, con carácter general, el monto de este complemento. Se pagará en partida separada, identificada en cada recibo como "Complemento del beneficio de alimentación". Todos los pagos se realizarán en Bolívares calculados a la tasa oficial del Banco Central de Venezuela (BCV) del día del pago.

SÉPTIMA: SEMANA ADICIONAL POR MES (PRESTACIONES, VACACIONES Y UTILIDADES). Cada cuatro (4) semanas trabajadas se genera a favor de EL TRABAJADOR el derecho a una (1) semana adicional, de monto fijo equivalente a {{CONTRATO_SEMANA_ADICIONAL_USD}} según el oficio (90,00 USD para ayudante y 115,00 USD para clasificado), pagadero en Bolívares a la tasa oficial del BCV del día del pago. Ese derecho se destina al pago de las prestaciones sociales, las vacaciones, el bono vacacional, las utilidades y demás conceptos que le correspondan conforme a la LOTTT y a la Convención Colectiva. Al sacar la cuenta, este beneficio es mayor que el que resultaría de pagar únicamente las alícuotas legales y convencionales de esos conceptos calculadas sobre el salario del Tabulador. El pago de las semanas adicionales causadas se efectuará al terminar la relación de trabajo (cierre de obra o finiquito), y no durante su vigencia. Al finiquito se pagará también la fracción que corresponda a las semanas trabajadas que no completen un ciclo de cuatro (4). En esa oportunidad el pago se imputa en este orden: a) a la garantía de prestaciones sociales, conforme al artículo 142 de la LOTTT y a la Cláusula 50 de la Convención Colectiva; b) a las utilidades de la Cláusula 48; c) a las vacaciones y al bono vacacional de la Cláusula 47; y d) el remanente, como complemento voluntario del beneficio de alimentación, sin carácter salarial. Cada recibo discriminará los conceptos.

OCTAVA: ÉTICA Y CONFIDENCIALIDAD. EL TRABAJADOR guardará reserva absoluta sobre la información técnica de la obra y se abstendrá de prácticas desleales.

NOVENA: TRANSPORTE GRATUITO (BENEFICIO SOCIAL NO REMUNERATIVO). LA ENTIDAD DE TRABAJO brindará de manera gratuita un servicio de transporte diario, de ida y vuelta, desde el punto de encuentro establecido {{OBRA_PUNTO_ENC_TRANSPORTE}} hasta el sitio de la obra. NATURALEZA JURÍDICA: conforme al artículo 105 de la LOTTT, este servicio es un beneficio social de carácter no remunerativo: no forma parte del salario, no es salario en especie y no se computará para prestaciones sociales, vacaciones, utilidades, bonos ni ningún otro concepto laboral. CONDICIONES: su uso es opcional para EL TRABAJADOR y está sujeto a las normas de conducta y seguridad dictadas por la empresa durante el trayecto.

DÉCIMA: DOMICILIO PROCESAL. Las partes eligen como domicilio especial la ciudad de {{CONTRATO_DOMICILIO_PROCESAL}}, Estado Nueva Esparta, sin perjuicio de la competencia que la Ley Orgánica Procesal del Trabajo atribuye a los Tribunales del Trabajo. Se firman dos (2) ejemplares de un mismo tenor y a un solo efecto, en {{CONTRATO_DOMICILIO_PROCESAL}}, a los {{CONTRATO_DIA_FIRMA}} días del mes de {{CONTRATO_MES_FIRMA}} del año {{CONTRATO_ANIO_FIRMA}}.

POR LA ENTIDAD DE TRABAJO                          POR EL TRABAJADOR

_______________________________                    _______________________________
{{REP_LEGAL_NOMBRE}}                               {{EMPLEADO_NOMBRE_COMPLETO}}
C.I. {{REP_LEGAL_CEDULA}}                          C.I. {{EMPLEADO_CEDULA}}
{{REP_LEGAL_CARGO}}                                (Huella dactilar)$cuerpo$,
    updated_at = now()
where codigo = 'contrato_obrero';
