/**
 * Catálogo de cargos de obreros (clasificación por grupos 1–9).
 * Códigos normalizados a forma «n.m» para consistencia en requisiciones.
 */
export const CATALOGO_OBREROS: { departamento: string; cargo: string }[] = [
  // Grupo 1
  { departamento: 'Grupo 1', cargo: '1.1 OBRERO DE 1era.' },
  { departamento: 'Grupo 1', cargo: '1.2 VIGILANTE' },
  // Grupo 2
  { departamento: 'Grupo 2', cargo: '2.1 AYUDANTE' },
  { departamento: 'Grupo 2', cargo: '2.2 AUXILIAR DE DEPOSITO' },
  { departamento: 'Grupo 2', cargo: '2.3 CHOFER DE 4ta.' },
  { departamento: 'Grupo 2', cargo: '2.4 OPERADOR DE MARTILLO PERFORADOR' },
  { departamento: 'Grupo 2', cargo: '2.5 AYUDANTE DE OPERADORES' },
  { departamento: 'Grupo 2', cargo: '2.6 AYUDANTE DE MECANICO DIESEL' },
  { departamento: 'Grupo 2', cargo: '2.7 AYUDANTE DE TOPOGRAFO' },
  { departamento: 'Grupo 2', cargo: '2.8 RASTRILLERO' },
  { departamento: 'Grupo 2', cargo: '2.9 ESPESORISTA' },
  { departamento: 'Grupo 2', cargo: '2.10 PALERO ASFALTICO' },
  // Grupo 3
  { departamento: 'Grupo 3', cargo: '3.1 CAPORAL' },
  { departamento: 'Grupo 3', cargo: '3.2 ALBAÑIL DE 2da.' },
  { departamento: 'Grupo 3', cargo: '3.3 CARPINTERO DE 2da.' },
  { departamento: 'Grupo 3', cargo: '3.4 CABILLERO DE 2da.' },
  { departamento: 'Grupo 3', cargo: '3.5 PLOMERO DE 2da.' },
  { departamento: 'Grupo 3', cargo: '3.6 ELECTRICISTA DE 2da.' },
  { departamento: 'Grupo 3', cargo: '3.7 GRANITERO DE 2da.' },
  { departamento: 'Grupo 3', cargo: '3.8 PINTOR DE 2da.' },
  { departamento: 'Grupo 3', cargo: '3.9 IMPERMEABILIZADOR DE 2da.' },
  { departamento: 'Grupo 3', cargo: '3.10 GÜINCHERO' },
  { departamento: 'Grupo 3', cargo: '3.11 MAQUINISTA DE CONCRETO DE 2da.' },
  { departamento: 'Grupo 3', cargo: '3.12 OPERADOR DE PLANTA FIJA DE 2da.' },
  { departamento: 'Grupo 3', cargo: '3.13 CHOFER DE 3ra. (HASTA 3 TONS)' },
  { departamento: 'Grupo 3', cargo: '3.14 OPERADOR DE EQUIPO PERFORADOR' },
  { departamento: 'Grupo 3', cargo: '3.15 OPERADOR DE EQUIPO LIVIANO' },
  { departamento: 'Grupo 3', cargo: '3.16 ENGRASADOR' },
  { departamento: 'Grupo 3', cargo: '3.17 CAUCHERO' },
  { departamento: 'Grupo 3', cargo: '3.18 MECÁNICO DE GASOLINA DE 2da.' },
  { departamento: 'Grupo 3', cargo: '3.19 SOLDADOR DE 3ra.' },
  { departamento: 'Grupo 3', cargo: '3.20 LATONERO DE 2da.' },
  { departamento: 'Grupo 3', cargo: '3.21 INSTALADOR ELECTRICOMECANICO DE 2da.' },
  { departamento: 'Grupo 3', cargo: '3.22 OPERADOR EQUIPO DE SANDBLASTING' },
  // Grupo 4
  { departamento: 'Grupo 4', cargo: '4.1 MAQUINISTA DE CONCRETO DE 1ra.' },
  { departamento: 'Grupo 4', cargo: '4.2 OPERADOR DE PLANTA FIJA DE 1ra.' },
  { departamento: 'Grupo 4', cargo: '4.3 CHOFER DE 2da. (DE 3 A 8 TONS)' },
  { departamento: 'Grupo 4', cargo: '4.4 OPERADOR DE PALA HASTA 1YARDA CUB.' },
  { departamento: 'Grupo 4', cargo: '4.5 MECANICO DE GASOLINA DE 1ra.' },
  { departamento: 'Grupo 4', cargo: '4.6 SOLDADOR DE 2da.' },
  { departamento: 'Grupo 4', cargo: '4.7 OPERADOR DE PAVIMENTADORA' },
  // Grupo 5
  { departamento: 'Grupo 5', cargo: '5.1 ALBAÑIL DE 1ra.' },
  { departamento: 'Grupo 5', cargo: '5.2 CARPINTERO DE 1ra.' },
  { departamento: 'Grupo 5', cargo: '5.3 CABILLERO DE 1ra.' },
  { departamento: 'Grupo 5', cargo: '5.4 PLOMERO DE 1ra.' },
  { departamento: 'Grupo 5', cargo: '5.5 ELECTRICISTA DE 1ra.' },
  { departamento: 'Grupo 5', cargo: '5.6 GRANITERO DE 1ra.' },
  { departamento: 'Grupo 5', cargo: '5.7 PINTOR DE 1ra.' },
  { departamento: 'Grupo 5', cargo: '5.8 IMPERMEABILIZADOR DE 1ra.' },
  { departamento: 'Grupo 5', cargo: '5.9 CHOFER DE 1ra. (DE 8 A 15 TONS)' },
  { departamento: 'Grupo 5', cargo: '5.10 OPERADOR DE EQUIPO PESADO DE 2da.' },
  { departamento: 'Grupo 5', cargo: '5.11 TRACTORISTA DE 2da.' },
  { departamento: 'Grupo 5', cargo: '5.12 OPERADOR DE MOTOTRAILLA DE 2da.' },
  { departamento: 'Grupo 5', cargo: '5.13 OPERADOR DE MOTONIVELADORA DE 2da.' },
  { departamento: 'Grupo 5', cargo: '5.14 OPERADOR DE GRUA (GRUERO) DE 2da.' },
  { departamento: 'Grupo 5', cargo: '5.15 MECANICO EQUIPO PESADO DE 2da.' },
  { departamento: 'Grupo 5', cargo: '5.16 OPERADOR MAQUINAS-HERRAMIENTAS 2da.' },
  { departamento: 'Grupo 5', cargo: '5.17 SOLDADOR DE 1ra.' },
  { departamento: 'Grupo 5', cargo: '5.18 TUBERO FABRICADOR' },
  { departamento: 'Grupo 5', cargo: '5.19 MONTADOR' },
  { departamento: 'Grupo 5', cargo: '5.20 LATONERO DE 1ra.' },
  { departamento: 'Grupo 5', cargo: '5.21 INSTALADOR ELECTRICOMECANICO DE 1ra.' },
  { departamento: 'Grupo 5', cargo: '5.22 LINIERO DE 1ra.' },
  { departamento: 'Grupo 5', cargo: '5.23 ALBAÑIL REFRACTARIO' },
  { departamento: 'Grupo 5', cargo: '5.24 DEPOSITARIO' },
  { departamento: 'Grupo 5', cargo: '5.25 DUCTERO' },
  { departamento: 'Grupo 5', cargo: '5.26 ARMADOR METALICO' },
  // Grupo 6
  { departamento: 'Grupo 6', cargo: '6.1 MAESTRO CARPINTERO DE 2da.' },
  { departamento: 'Grupo 6', cargo: '6.2 CHOFER DE CAMIÓN MAS DE 15 TONS.' },
  { departamento: 'Grupo 6', cargo: '6.3 CHOFER DE GANDOLA DE 2da. (DE 15-40T)' },
  { departamento: 'Grupo 6', cargo: '6.4 CHOFER DE CAMIÓN MEZCLADOR' },
  { departamento: 'Grupo 6', cargo: '6.5 OPERADOR DE PALA MAS 1YARDA CUB.DE 2da.' },
  { departamento: 'Grupo 6', cargo: '6.6 PROYECTADOR DE CONCRETO' },
  { departamento: 'Grupo 6', cargo: '6.7 CHOFER DE VOLTEO DE 30 O MAS TONELADAS' },
  // Grupo 7
  { departamento: 'Grupo 7', cargo: '7.1 MAESTRO ALBAÑIL' },
  { departamento: 'Grupo 7', cargo: '7.2 MAESTRO CARPINTERO DE 1ra.' },
  { departamento: 'Grupo 7', cargo: '7.3 MAESTRO CABILLERO' },
  { departamento: 'Grupo 7', cargo: '7.4 MAESTRO PLOMERO DE 1ra.' },
  { departamento: 'Grupo 7', cargo: '7.5 MAESTRO ELECTRICISTA' },
  { departamento: 'Grupo 7', cargo: '7.6 MAESTRO GRANITERO' },
  { departamento: 'Grupo 7', cargo: '7.7 MAESTRO PINTOR' },
  { departamento: 'Grupo 7', cargo: '7.8 MAESTRO IMPERMEABILIZADOR' },
  { departamento: 'Grupo 7', cargo: '7.9 MAESTRO DE OBRA DE 2da.' },
  { departamento: 'Grupo 7', cargo: '7.10 CHOFER DE GANDOLA DE 1ra. (TODO TON.)' },
  { departamento: 'Grupo 7', cargo: '7.11 DINAMITERO' },
  { departamento: 'Grupo 7', cargo: '7.12 CAPORAL DE EQUIPO' },
  { departamento: 'Grupo 7', cargo: '7.13 MAESTRO DE OBRAS ELECTROMECANICAS' },
  { departamento: 'Grupo 7', cargo: '7.14 ALINEADOR DE GRUA (REGGE)' },
  { departamento: 'Grupo 7', cargo: '7.15 MINERO' },
  // Grupo 8
  { departamento: 'Grupo 8', cargo: '8.1 MAESTRO DE VOLADURAS' },
  { departamento: 'Grupo 8', cargo: '8.2 OPERADOR DE EQUIPO PESADO DE 1ra.' },
  { departamento: 'Grupo 8', cargo: '8.3 TRACTORISTA DE 1ra.' },
  { departamento: 'Grupo 8', cargo: '8.4 OPERADOR DE MOTOTRAILLA DE 1ra.' },
  { departamento: 'Grupo 8', cargo: '8.5 OPERADOR DE PALA MAS 1YARDA CUB. DE 1ra.' },
  { departamento: 'Grupo 8', cargo: '8.6 OPERADOR DE MOTONIVELADORA DE 1ra.' },
  { departamento: 'Grupo 8', cargo: '8.7 OPERADOR DE GRÚA (GRUERO) DE 1ra.' },
  { departamento: 'Grupo 8', cargo: '8.8 MECÁNICO EQUIPO PESADO DE 1ra.' },
  { departamento: 'Grupo 8', cargo: '8.9 OPERADOR MÁQUINAS-HERRAMIENTAS 1ra.' },
  { departamento: 'Grupo 8', cargo: '8.10 OPERADOR DE PLANTA' },
  { departamento: 'Grupo 8', cargo: '8.11 OPERADOR DE ALIVA' },
  // Grupo 9
  { departamento: 'Grupo 9', cargo: '9.1 MAESTRO DE OBRA DE 1ra.' },
  { departamento: 'Grupo 9', cargo: '9.2 MAESTRO MECÁNICO' },
]
